import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,validateState,calculate,dateISO,moneyWeightedReturn,householdMonthlyHistory} from '../lib/portfolio.mjs';
import {DEFAULT_FINANCE,accountBalances,addMonthlyRecurring,importPreviewRows,installmentSchedule,invoiceSummaries,parseStatementCsv,summarizeFinance,validateFinance} from '../lib/finance.mjs';

const base=()=>{const state=initialState();state.finance=DEFAULT_FINANCE();state.finance.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:dateISO()}];return state;};
test('transferência entre contas não vira receita ou despesa e preserva o saldo consolidado',()=>{const s=base();s.finance.accounts.push({id:'cash',name:'Dinheiro',type:'cash',openingBalance:100,openingDate:dateISO()});s.finance.transactions=[{id:'t',type:'transfer',accountId:'bank',toAccountId:'cash',amount:200,date:dateISO(),description:'Saque'}];const sum=summarizeFinance(s.finance);assert.equal(sum.cash,1100);assert.equal(sum.income,0);assert.equal(sum.expenses,0);assert.equal(sum.netCashFlow,0);assert.equal(validateState(s),s);});
test('pagamento da fatura não duplica a despesa e reduz conta e fatura',()=>{const s=base();s.finance.cards=[{id:'card',name:'Visa',accountId:'bank',closeDay:10,dueDay:20}];const parts=installmentSchedule({date:dateISO(),amount:120,installments:1,closeDay:10,dueDay:20});const invoiceMonth=parts[0].invoiceMonth;s.finance.transactions=[{id:'buy',type:'card_purchase',cardId:'card',amount:120,date:dateISO(),description:'Mercado',category:'Alimentação',installments:1,invoiceMonth,closeDay:10,dueDay:20,installmentParts:parts},{id:'pay',type:'card_payment',cardId:'card',accountId:'bank',amount:120,date:dateISO(),description:'Fatura',invoiceMonth}];const sum=summarizeFinance(s.finance,dateISO().slice(0,7));assert.equal(sum.expenses,120);assert.equal(sum.balances.bank,880);assert.equal(invoiceSummaries(s.finance)[0].open,0);assert.equal(sum.netCashFlow,-120);validateState(s);});
test('compras parceladas distribuem valores e vencimentos pelas faturas',()=>{const parts=installmentSchedule({date:'2026-01-05',amount:100,installments:3,closeDay:10,dueDay:20});assert.deepEqual(parts.map(p=>p.invoiceMonth),['2026-01','2026-02','2026-03']);assert.equal(parts.reduce((n,p)=>n+p.amount,0),100);assert.deepEqual(parts.map(p=>p.dueDate),['2026-01-20','2026-02-20','2026-03-20']);});
test('CSV aceita ponto e vírgula, decimal brasileiro e campos com aspas',()=>{const rows=parseStatementCsv('Data;Descrição;Valor\n01/01/2026;"Mercado; central";-1.234,56\n02/01/2026;Salário;5.000,00');assert.equal(rows.length,2);assert.equal(rows[0].description,'Mercado; central');assert.equal(rows[0].amount,1234.56);assert.equal(rows[0].type,'expense');assert.equal(rows[1].amount,5000);assert.equal(rows[1].type,'income');});
test('prévia marca repetidos e linhas inválidas sem selecioná-los',()=>{const rows=parseStatementCsv(`Data,Descrição,Valor\n01/01/2026,Mercado,-10`);const existing=[{...rows[0],id:'old'}];const preview=importPreviewRows(rows,existing);assert.equal(preview[0].duplicate,true);assert.equal(preview[0].selected,false);assert.equal(importPreviewRows([{...rows[0],valid:false}],[])[0].selected,false);});
test('CSV sinaliza transferências suspeitas e ocorrências duplicadas dentro do mesmo arquivo',()=>{const rows=parseStatementCsv(`Data,Descrição,Valor\n01/01/2026,PIX recebido,-10\n02/01/2026,Mercado,-10\n02/01/2026,Mercado,-10`);assert.equal(rows[0].possibleTransfer,true);assert.equal(rows[0].valid,false);const preview=importPreviewRows(rows,[]);assert.equal(preview[1].selected,true);assert.equal(preview[2].duplicate,true);assert.equal(preview[2].selected,false);});
test('recorrências mensais geram lançamento uma vez por competência',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:0,openingDate:dateISO()}];f.recurring=[{id:'rent',type:'expense',accountId:'bank',amount:1200,description:'Aluguel',category:'Moradia',day:1}];const month=dateISO().slice(0,7);const first=addMonthlyRecurring(f,month);assert.equal(first.added,1);const second=addMonthlyRecurring(first.finance,month);assert.equal(second.added,0);});
test('rentabilidade pessoal conta aportes e retiradas, mas ignora dividendos como capital externo',()=>{const s=base();const yesterday=new Date(`${dateISO()}T12:00:00Z`);yesterday.setUTCDate(yesterday.getUTCDate()-1);s.startDate=yesterday.toISOString().slice(0,10);s.assets[0].initial=0;s.events=[{id:'a',date:s.startDate,kind:'aporte',assetId:'cdb-santander',amount:1000},{id:'d',date:dateISO(),kind:'dividendo',assetId:'cdb-santander',amount:10}];assert.ok(moneyWeightedReturn(s));assert.ok(moneyWeightedReturn(s).total>0);assert.equal(calculate(s).gain,10);});
test('patrimônio mensal da família soma investimentos e caixa e desconta a fatura sem duplicar aporte interno',()=>{const s=base();const event={id:'aporte-via-conta',date:dateISO(),kind:'aporte',assetId:'cdb-santander',amount:500};s.events.push(event);s.finance.transactions.push({id:'inv',type:'investment',accountId:'bank',assetId:'cdb-santander',portfolioEventId:event.id,amount:500,date:dateISO(),description:'Aporte no CDB'});const history=householdMonthlyHistory(s);assert.equal(history.at(-1).total,6700);assert.equal(history.at(-1).invested,6700);});
test('dados financeiros inválidos são rejeitados',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'a',name:'Conta',type:'checking',openingBalance:NaN,openingDate:dateISO()}];assert.throws(()=>validateFinance(f));});
