import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,validateState,calculate,dateISO,moneyWeightedReturn,householdMonthlyHistory} from '../lib/portfolio.mjs';
import {DEFAULT_FINANCE,accountBalances,addMonthlyRecurring,closeFinanceMonth,filterFinanceTransactions,financeForecast,financeMonthClosing,importPreviewRows,installmentSchedule,invoiceSummaries,monthEnd,parseStatementCsv,reconcileFinanceDuplicate,reopenFinanceMonth,summarizeFinance,portfolioContributionRows,upcomingFinanceObligations,validateFinance} from '../lib/finance.mjs';
import {applyRule,previewRule} from '../lib/pluggy-sync.mjs';
import {mergePluggyData} from '../lib/pluggy-sync.mjs';

test('aporte à carteira entra no total financeiro sem alterar o fluxo ou saldo sem débito',()=>{
 const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Conta',type:'checking',openingBalance:1000,openingDate:'2026-01-01'}];f.transactions=[{id:'income',type:'income',accountId:'bank',amount:500,date:'2026-09-02',description:'Salário',category:'Salário'},{id:'debit',type:'investment',accountId:'bank',amount:100,date:'2026-09-10',description:'Aplicação',category:'Investimento',assetId:'fund',portfolioEventId:'linked'}];
 const events=[{id:'linked',kind:'aporte',assetId:'fund',amount:100,date:'2026-09-10'},{id:'outside',kind:'aporte',assetId:'fund',amount:50,date:'2026-09-15'}];
 const summary=summarizeFinance(f,'2026-09','2026-09-30',events);
 assert.equal(summary.investments,150);assert.equal(summary.cashInvestments,100);assert.deepEqual(portfolioContributionRows(events,f,'2026-09').map(e=>e.portfolioEventId),['outside']);assert.equal(summary.netCashFlow,400);assert.equal(accountBalances(f,'2026-09-30').bank,1400);
});

test('fechamento mensal preserva o retrato e sinaliza alterações posteriores',()=>{
 const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Conta',type:'checking',openingBalance:1000,openingDate:'2026-01-01'}];f.transactions=[{id:'expense',type:'expense',accountId:'bank',amount:100,date:'2026-01-10',description:'Conta',category:'Moradia'}];
 const closed=closeFinanceMonth(f,'2026-01','2026-02-01T12:00:00.000Z');
 assert.equal(financeMonthClosing(closed,'2026-01').closed,true);
 assert.equal(financeMonthClosing(closed,'2026-01').stale,false);
 assert.equal(validateFinance(closed),true);
 closed.transactions[0].amount=120;
 assert.equal(financeMonthClosing(closed,'2026-01').stale,true);
 assert.equal(financeMonthClosing(reopenFinanceMonth(closed,'2026-01'),'2026-01').closed,false);
 assert.throws(()=>closeFinanceMonth({...f,transactions:[{...f.transactions[0],needsReview:true}]},'2026-01'),/pendências/i);
 assert.throws(()=>closeFinanceMonth(f,dateISO().slice(0,7)),/encerrados/i);
});

test('próximos vencimentos não repetem recorrência já lançada e exibem fatura em aberto',()=>{
 const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Conta',type:'checking',openingBalance:1000,openingDate:'2026-01-01'}];f.cards=[{id:'card',name:'Visa',accountId:'bank',closeDay:10,dueDay:20}];
 f.recurring=[{id:'rent',type:'expense',accountId:'bank',amount:300,description:'Aluguel',category:'Moradia',day:5}];
 f.transactions=[{id:'rent-posted',type:'expense',accountId:'bank',amount:300,date:'2026-01-05',description:'Aluguel',category:'Moradia',recurringId:'rent'},{id:'purchase',type:'card_purchase',cardId:'card',amount:200,date:'2026-01-05',description:'Mercado',category:'Alimentação',installments:1,closeDay:10,dueDay:20,invoiceMonth:'2026-01'}];
 const obligations=upcomingFinanceObligations(f,'2026-01-01',60);
 assert.equal(obligations.some(item=>item.id==='recurring:rent:2026-01'),false);
 assert.equal(obligations.some(item=>item.id==='recurring:rent:2026-02'),true);
 assert.equal(obligations.some(item=>item.id==='invoice:card:2026-01'),true);
});

test('filtros distinguem cartão de conta e estados de revisão',()=>{
 const f=DEFAULT_FINANCE();f.transactions=[{id:'bank',type:'expense',accountId:'a',amount:20,date:'2026-01-02',description:'Uber',category:'Transporte'},{id:'card',type:'card_purchase',accountId:'a',cardId:'c',amount:30,date:'2026-01-03',description:'Mercado',category:'Alimentação',needsReview:true},{id:'other',type:'expense',accountId:'b',amount:10,date:'2026-01-04',description:'Luz',category:'Energia'}];
 assert.deepEqual(filterFinanceTransactions(f,'2026-01',{source:'account:a'}).map(t=>t.id),['bank']);
 assert.deepEqual(filterFinanceTransactions(f,'2026-01',{source:'card:c',status:'pending'}).map(t=>t.id),['card']);
 assert.deepEqual(filterFinanceTransactions(f,'2026-01',{search:'UBER'}).map(t=>t.id),['bank']);
});

test('duplicado sincronizado vincula lançamento manual sem duplicar saldo ou despesa',()=>{
 const state=initialState(),today=dateISO();state.finance=DEFAULT_FINANCE();state.finance.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:today,pluggyAccountId:'remote'}];state.finance.transactions=[{id:'manual',type:'expense',accountId:'bank',amount:50,date:today,description:'Mercado',category:'Alimentação'}];
 const payload={itemId:'item',updatedAt:new Date().toISOString(),accounts:[{id:'remote',name:'Santander',type:'CHECKING_ACCOUNT',balance:950,transactions:[{id:'remote-1',type:'DEBIT',date:today,description:'Mercado',amount:-50,status:'POSTED'}]}]};
 const merged=mergePluggyData(state,payload),remote=merged.finance.transactions.find(t=>t.pluggyTransactionId==='remote-1');
 assert.equal(remote.matchingManualTransactionId,'manual');
 const linked=reconcileFinanceDuplicate(merged.finance,remote.id);
 assert.equal(summarizeFinance(linked).cash,950);
 assert.equal(summarizeFinance(linked).expenses,50);
 assert.equal(summarizeFinance(linked).review.count,0);
 const again=mergePluggyData({...state,finance:linked},payload);
 assert.equal(again.finance.transactions.find(t=>t.pluggyTransactionId==='remote-1').needsReview,false);
});

test('compra no cartão é gasto no mês, mas só altera o fluxo de caixa no pagamento',()=>{
 const f=DEFAULT_FINANCE();
 f.accounts=[{id:'bank',name:'Conta',type:'checking',openingBalance:1000,openingDate:'2026-01-01'}];
 f.cards=[{id:'card',name:'Visa',accountId:'bank',closeDay:10,dueDay:20}];
 f.transactions=[{id:'purchase',type:'card_purchase',cardId:'card',amount:200,date:'2026-01-05',description:'Mercado',category:'Alimentação',installments:1,closeDay:10,dueDay:20,invoiceMonth:'2026-01'}];
 const jan=summarizeFinance(f,'2026-01','2026-01-31');
 assert.equal(jan.expenses,200);
 assert.equal(jan.netCashFlow,0);
 assert.equal(jan.cash,1000);
 f.transactions.push({id:'payment',type:'card_payment',cardId:'card',accountId:'bank',amount:200,date:'2026-02-20',description:'Fatura',invoiceMonth:'2026-01'});
 const feb=summarizeFinance(f,'2026-02','2026-02-28');
 assert.equal(feb.expenses,0);
 assert.equal(feb.cardPayments,200);
 assert.equal(feb.netCashFlow,-200);
 assert.equal(feb.cash,800);
});

test('previsão não desconta novamente recorrência já lançada no mês atual',()=>{
 const today=dateISO(),month=today.slice(0,7),f=DEFAULT_FINANCE();
 f.accounts=[{id:'bank',name:'Conta',type:'checking',openingBalance:1000,openingDate:today}];
 f.recurring=[{id:'rent',type:'expense',accountId:'bank',amount:100,description:'Aluguel',category:'Moradia',day:5}];
 f.transactions=[{id:'posted',type:'expense',accountId:'bank',amount:100,date:today,description:'Aluguel',category:'Moradia',recurringId:'rent'}];
 const forecast=financeForecast(f,month,2);
 assert.equal(forecast.opening,900);
 assert.equal(forecast.months[0].recurringExpenses,0);
 assert.equal(forecast.months[0].closing,900);
 assert.equal(forecast.months[1].recurringExpenses,100);
 assert.equal(forecast.months[1].closing,800);
});

test('sincronização repetida mantém decisões de revisão e aporte conciliado',()=>{
 const s=initialState(),today=dateISO(),payload={itemId:'item',updatedAt:new Date().toISOString(),accounts:[{id:'remote',name:'Santander',type:'CHECKING_ACCOUNT',balance:900,transactions:[{id:'expense',date:today,description:'PIX recebido?',amount:-50,type:'DEBIT'},{id:'cdb',date:today,description:'APLICACAO CDB/RDB',amount:-100,type:'DEBIT'}]}]};
 const first=mergePluggyData(s,payload),finance=first.finance;
 const expense=finance.transactions.find(t=>t.pluggyTransactionId==='expense'),cdb=finance.transactions.find(t=>t.pluggyTransactionId==='cdb');
 expense.needsReview=false;expense.reviewDecision='excluded';expense.excludedFromBalances=true;
 cdb.needsReview=false;cdb.reconciled=true;cdb.portfolioEventId='manual-event';
 const again=mergePluggyData({...s,finance},payload);
 assert.equal(again.finance.transactions.find(t=>t.pluggyTransactionId==='expense').needsReview,false);
 assert.equal(again.finance.transactions.find(t=>t.pluggyTransactionId==='expense').excludedFromBalances,true);
 assert.equal(again.finance.transactions.find(t=>t.pluggyTransactionId==='cdb').needsReview,false);
 assert.equal(again.imported,0);
});

const base=()=>{const state=initialState();state.finance=DEFAULT_FINANCE();state.finance.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:dateISO()}];return state;};
test('transferência entre contas não vira receita ou despesa e preserva o saldo consolidado',()=>{const s=base();s.finance.accounts.push({id:'cash',name:'Dinheiro',type:'cash',openingBalance:100,openingDate:dateISO()});s.finance.transactions=[{id:'t',type:'transfer',accountId:'bank',toAccountId:'cash',amount:200,date:dateISO(),description:'Saque'}];const sum=summarizeFinance(s.finance);assert.equal(sum.cash,1100);assert.equal(sum.income,0);assert.equal(sum.expenses,0);assert.equal(sum.netCashFlow,0);assert.equal(validateState(s),s);});
test('pagamento da fatura não duplica a despesa e reduz conta e fatura',()=>{const s=base();s.finance.cards=[{id:'card',name:'Visa',accountId:'bank',closeDay:10,dueDay:20}];const parts=installmentSchedule({date:dateISO(),amount:120,installments:1,closeDay:10,dueDay:20});const invoiceMonth=parts[0].invoiceMonth;s.finance.transactions=[{id:'buy',type:'card_purchase',cardId:'card',amount:120,date:dateISO(),description:'Mercado',category:'Alimentação',installments:1,invoiceMonth,closeDay:10,dueDay:20,installmentParts:parts},{id:'pay',type:'card_payment',cardId:'card',accountId:'bank',amount:120,date:dateISO(),description:'Fatura',invoiceMonth}];const sum=summarizeFinance(s.finance,dateISO().slice(0,7));assert.equal(sum.expenses,120);assert.equal(sum.balances.bank,880);assert.equal(invoiceSummaries(s.finance)[0].open,0);assert.equal(sum.netCashFlow,-120);validateState(s);});
test('compras parceladas distribuem valores e vencimentos pelas faturas',()=>{const parts=installmentSchedule({date:'2026-01-05',amount:100,installments:3,closeDay:10,dueDay:20});assert.deepEqual(parts.map(p=>p.invoiceMonth),['2026-01','2026-02','2026-03']);assert.equal(parts.reduce((n,p)=>n+p.amount,0),100);assert.deepEqual(parts.map(p=>p.dueDate),['2026-01-20','2026-02-20','2026-03-20']);});
test('CSV aceita ponto e vírgula, decimal brasileiro e campos com aspas',()=>{const rows=parseStatementCsv('Data;Descrição;Valor\n01/01/2026;"Mercado; central";-1.234,56\n02/01/2026;Salário;5.000,00');assert.equal(rows.length,2);assert.equal(rows[0].description,'Mercado; central');assert.equal(rows[0].amount,1234.56);assert.equal(rows[0].type,'expense');assert.equal(rows[1].amount,5000);assert.equal(rows[1].type,'income');});
test('prévia marca repetidos e linhas inválidas sem selecioná-los',()=>{const rows=parseStatementCsv(`Data,Descrição,Valor\n01/01/2026,Mercado,-10`);const existing=[{...rows[0],id:'old'}];const preview=importPreviewRows(rows,existing);assert.equal(preview[0].duplicate,true);assert.equal(preview[0].selected,false);assert.equal(importPreviewRows([{...rows[0],valid:false}],[])[0].selected,false);});
test('CSV sinaliza transferências suspeitas e ocorrências duplicadas dentro do mesmo arquivo',()=>{const rows=parseStatementCsv(`Data,Descrição,Valor\n01/01/2026,PIX recebido,-10\n02/01/2026,Mercado,-10\n02/01/2026,Mercado,-10`);assert.equal(rows[0].possibleTransfer,true);assert.equal(rows[0].valid,false);const preview=importPreviewRows(rows,[]);assert.equal(preview[1].selected,true);assert.equal(preview[2].duplicate,true);assert.equal(preview[2].selected,false);});
test('recorrências mensais geram lançamento uma vez por competência',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:0,openingDate:dateISO()}];f.recurring=[{id:'rent',type:'expense',accountId:'bank',amount:1200,description:'Aluguel',category:'Moradia',day:1}];const month=dateISO().slice(0,7);const first=addMonthlyRecurring(f,month);assert.equal(first.added,1);const second=addMonthlyRecurring(first.finance,month);assert.equal(second.added,0);});
test('rentabilidade pessoal conta aportes e retiradas, mas ignora dividendos como capital externo',()=>{const s=base();const yesterday=new Date(`${dateISO()}T12:00:00Z`);yesterday.setUTCDate(yesterday.getUTCDate()-1);s.startDate=yesterday.toISOString().slice(0,10);s.assets[0].initial=0;s.events=[{id:'a',date:s.startDate,kind:'aporte',assetId:'cdb-santander',amount:1000},{id:'d',date:dateISO(),kind:'dividendo',assetId:'cdb-santander',amount:10}];assert.ok(moneyWeightedReturn(s));assert.ok(moneyWeightedReturn(s).total>0);assert.equal(calculate(s).gain,10);});
test('aportes via conta entram na carteira uma única vez, sem somar saldos bancários',()=>{const s=base();const event={id:'aporte-via-conta',date:dateISO(),kind:'aporte',assetId:'cdb-santander',amount:500};s.events.push(event);s.finance.transactions.push({id:'inv',type:'investment',accountId:'bank',assetId:'cdb-santander',portfolioEventId:event.id,amount:500,date:dateISO(),description:'Aporte no CDB'});const history=householdMonthlyHistory(s);assert.equal(history.at(-1).total,calculate(s).total);assert.equal(history.at(-1).invested,calculate(s).total- calculate(s).gain);assert.equal(summarizeFinance(s.finance).cash,500);});
test('receitas aumentam o caixa e o fluxo mensal, sem alterar patrimônio investido',()=>{const s=base(),before=calculate(s).total;s.finance.transactions.push({id:'salary',type:'income',accountId:'bank',amount:2500,date:dateISO(),description:'Salário'});assert.equal(summarizeFinance(s.finance).cash,3500);assert.equal(summarizeFinance(s.finance).income,2500);assert.equal(calculate(s).total,before);assert.equal(householdMonthlyHistory(s).at(-1).total,before);});
test('resumo financeiro respeita competência selecionada e saldo no fim do mês',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:'2025-01-01'}];f.transactions=[{id:'jan',type:'income',accountId:'bank',amount:500,date:'2026-01-15',description:'Salário'},{id:'feb',type:'expense',accountId:'bank',amount:100,date:'2026-02-10',description:'Conta'}];const jan=summarizeFinance(f,'2026-01','2026-01-31'),feb=summarizeFinance(f,'2026-02','2026-02-28');assert.equal(jan.income,500);assert.equal(jan.expenses,0);assert.equal(jan.cash,1500);assert.equal(feb.income,0);assert.equal(feb.expenses,100);assert.equal(feb.cash,1400);});
test('Meu Pluggy importa contas e deduplica transações, marcando transferências e categorias desconhecidas',()=>{const s=base(),payload={itemId:'pluggy-item',updatedAt:'2026-09-24T12:00:00.000Z',accounts:[{id:'remote-bank',name:'Conta Corrente',type:'CHECKING_ACCOUNT',balance:850,transactions:[{id:'remote-1',date:dateISO(),description:'Mercado Central',amount:-100,type:'DEBIT',category:'Groceries',status:'POSTED'},{id:'remote-2',date:dateISO(),description:'PIX enviado',amount:-50,type:'DEBIT',category:null,status:'POSTED'}]}]};const first=mergePluggyData(s,payload);assert.equal(first.imported,2);assert.equal(first.finance.accounts[0].openingBalance,1000);assert.equal(first.finance.transactions[0].category,'Alimentação');assert.equal(first.finance.transactions[1].needsReview,true);assert.equal(first.finance.transactions[1].possibleTransfer,true);const second=mergePluggyData({...s,finance:first.finance},payload);assert.equal(second.imported,0);assert.equal(second.finance.transactions.length,2);});
test('Meu Pluggy importa histórico desde agosto mesmo quando a carteira começou depois',()=>{const s=base();s.finance.accounts.push({id:'pluggy-bank',name:'Santander importado',type:'checking',openingBalance:850,openingDate:dateISO(),pluggyAccountId:'remote-bank'});s.finance.transactions.push({id:'yesterday',type:'income',accountId:'pluggy-bank',amount:100,date:dateISO(),description:'Crédito',pluggyTransactionId:'remote-yesterday'});const payload={itemId:'pluggy-item',updatedAt:'2026-09-24T12:00:00.000Z',coverageStart:'2026-08-01',accounts:[{id:'remote-bank',name:'Conta Corrente',type:'CHECKING_ACCOUNT',balance:850,transactions:[{id:'remote-aug',date:'2026-08-15',description:'Mercado agosto',amount:-100,type:'DEBIT',status:'POSTED'},{id:'remote-yesterday',date:dateISO(),description:'Crédito',amount:100,type:'CREDIT',status:'POSTED'}]}]};const result=mergePluggyData(s,payload);assert.equal(result.imported,1);assert.equal(result.finance.transactions.find(t=>t.pluggyTransactionId==='remote-aug').date,'2026-08-15');assert.equal(result.finance.accounts.find(a=>a.pluggyAccountId==='remote-bank').openingDate,'2026-08-15');assert.equal(validateState({...s,finance:result.finance}).finance.transactions.length,2);});
test('Meu Pluggy classifica aplicações como aportes e reconhece categorias recorrentes',()=>{const s=base(),payload={itemId:'pluggy-item',updatedAt:new Date().toISOString(),accounts:[{id:'remote-bank',name:'Santander',type:'CHECKING_ACCOUNT',balance:7000,transactions:[{id:'cdb',date:dateISO(),description:'APLICACAO CDB/RDB',amount:-1600,type:'DEBIT',category:'Yield',status:'POSTED'},{id:'uber',date:dateISO(),description:'UBER TRIP',amount:-25,type:'DEBIT',status:'POSTED'},{id:'tithe',date:dateISO(),description:'IGREJA UNIVERSAL DO REINO',amount:-100,type:'DEBIT',status:'POSTED'},{id:'home',date:dateISO(),description:'EEVIR DEV CONDOMINIO',amount:-900,type:'DEBIT',status:'POSTED'}]}]};const result=mergePluggyData(s,payload),f=result.finance,byId=Object.fromEntries(f.transactions.map(t=>[t.pluggyTransactionId,t]));assert.equal(byId.cdb.type,'investment');assert.equal(byId.cdb.category,'Investimento');assert.equal(byId.cdb.bankInvestment,true);assert.equal(byId.uber.category,'Transporte');assert.equal(byId.tithe.category,'Dízimo/Oferta');assert.equal(byId.home.category,'Moradia');assert.equal(summarizeFinance(f,dateISO().slice(0,7)).review.count,1);assert.equal(summarizeFinance(f,dateISO().slice(0,7)).expenses,1025);validateState({...s,finance:f});});
test('sincronização posterior respeita categoria editada manualmente',()=>{const s=base(),payload={itemId:'pluggy-item',updatedAt:new Date().toISOString(),accounts:[{id:'remote-bank',name:'Santander',type:'CHECKING_ACCOUNT',balance:0,transactions:[{id:'uber',date:dateISO(),description:'UBER TRIP',amount:-25,type:'DEBIT',status:'POSTED'}]}]};const first=mergePluggyData(s,payload);first.finance.transactions[0].category='Lazer';first.finance.transactions[0].categoryManuallySet=true;const second=mergePluggyData({...s,finance:first.finance},payload);assert.equal(second.finance.transactions[0].category,'Lazer');});
test('sincronização corrige aplicações CDB já importadas como rendimento',()=>{const s=base();s.finance.accounts.push({id:'bank-pluggy',name:'Santander',type:'checking',openingBalance:0,openingDate:dateISO(),pluggyAccountId:'remote-bank'});s.finance.transactions.push({id:'old-cdb',type:'expense',accountId:'bank-pluggy',amount:1600,date:dateISO(),description:'APLICACAO CDB/RDB',category:'Rendimentos',pluggyTransactionId:'cdb'});const payload={itemId:'pluggy-item',updatedAt:new Date().toISOString(),accounts:[{id:'remote-bank',name:'Santander',type:'CHECKING_ACCOUNT',balance:0,transactions:[{id:'cdb',date:dateISO(),description:'APLICACAO CDB/RDB',amount:-1600,type:'DEBIT',category:'Yield',status:'POSTED'}]}]};const result=mergePluggyData(s,payload),tx=result.finance.transactions.find(t=>t.id==='old-cdb');assert.equal(tx.type,'investment');assert.equal(tx.category,'Investimento');assert.equal(summarizeFinance(result.finance,dateISO().slice(0,7)).review.count,1);validateState({...s,finance:result.finance});});
test('pendências são excluídas dos totais definitivos, mas afetam o saldo da conta',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:dateISO()}];f.transactions=[{id:'income',type:'income',accountId:'bank',amount:200,date:dateISO(),description:'Salário'},{id:'review',type:'expense',accountId:'bank',amount:80,date:dateISO(),description:'PIX recebido?',needsReview:true}];const result=summarizeFinance(f);assert.equal(result.income,200);assert.equal(result.expenses,0);assert.equal(result.review.count,1);assert.equal(result.cash,1120);});
test('previsão de seis meses inclui recorrências e faturas sem contar orçamento como gasto',()=>{const f=DEFAULT_FINANCE(),m=dateISO().slice(0,7);f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:dateISO()}];f.recurring=[{id:'salary',type:'income',accountId:'bank',amount:2000,description:'Salário',category:'Salário',day:5},{id:'rent',type:'expense',accountId:'bank',amount:1000,description:'Aluguel',category:'Moradia',day:5}];f.budgets[m]={Moradia:9000};const plan=financeForecast(f,m,6);assert.equal(plan.months.length,6);assert.equal(plan.months[0].income,2000);assert.equal(plan.months[0].recurringExpenses,1000);assert.equal(plan.months[0].budgetReference,9000);assert.equal(plan.months[5].closing,7000);});
test('faturas Pluggy vinculadas aparecem no mês e na previsão sem virar lançamento confirmado',()=>{const f=DEFAULT_FINANCE(),m=dateISO().slice(0,7);f.accounts=[{id:'bank',name:'Santander',type:'checking',openingBalance:1000,openingDate:dateISO()}];f.cards=[{id:'card',name:'Visa',accountId:'bank',closeDay:10,dueDay:20}];f.pluggy={cardLinks:{'remote-card':{cardId:'card'}},bills:[{id:'bill',accountId:'remote-card',dueDate:`${m}-20`,totalAmount:500,payments:[{amount:100}]}]};const invoices=invoiceSummaries(f,monthEnd(m));assert.equal(invoices[0].open,400);assert.equal(summarizeFinance(f,m).due,400);const forecast=financeForecast(f,m,1);assert.equal(forecast.months[0].knownBills,400);assert.equal(f.transactions.length,0);});
test('regra de categoria tem prévia e não sobrescreve categorias corrigidas manualmente',()=>{const state=base();state.finance.transactions=[{id:'a',type:'expense',accountId:'bank',amount:10,date:dateISO(),description:'UBER TRIP',category:'Outros'},{id:'b',type:'expense',accountId:'bank',amount:10,date:dateISO(),description:'UBER EATS',category:'Alimentação',categoryManuallySet:true}];const preview=previewRule(state,'uber','Transporte');assert.deepEqual(preview.map(r=>r.id),['a']);const next=applyRule(state,{id:'uber',contains:'uber',category:'Transporte',active:true},['a','b']);assert.equal(next.finance.transactions[0].category,'Transporte');assert.equal(next.finance.transactions[1].category,'Alimentação');});
test('aplicação sincronizada sugere conciliação por data e valor sem vincular automaticamente',()=>{const state=base(),event={id:'manual-event',date:dateISO(),kind:'aporte',assetId:'cdb-santander',amount:250};state.events.push(event);const payload={itemId:'pluggy-item',updatedAt:new Date().toISOString(),accounts:[{id:'remote-bank',name:'Santander',type:'CHECKING_ACCOUNT',balance:750,transactions:[{id:'cdb-link',date:dateISO(),description:'APLICACAO CDB/RDB',amount:-250,type:'DEBIT'}]}]},result=mergePluggyData(state,payload),tx=result.finance.transactions[0];assert.equal(tx.suggestedPortfolioEventId,event.id);assert.equal(tx.needsReview,true);assert.equal(result.events.filter(e=>e.kind==='aporte').length,1);});
test('aplicação bancária permanece em revisão sem duplicar aporte até confirmar posição',()=>{const state=base(),payload={itemId:'pluggy-item',updatedAt:new Date().toISOString(),accounts:[{id:'remote-bank',name:'Santander',type:'CHECKING_ACCOUNT',balance:800,transactions:[{id:'cdb-new',date:dateISO(),description:'APLICACAO CDB/RDB',amount:-200,type:'DEBIT'}]}]},result=mergePluggyData(state,payload),tx=result.finance.transactions[0];assert.equal(tx.needsReview,true);assert.equal(result.events.length,0);assert.equal(summarizeFinance(result.finance).investments,0);assert.equal(summarizeFinance(result.finance).cash,1800);});test('dados financeiros inválidos são rejeitados',()=>{const f=DEFAULT_FINANCE();f.accounts=[{id:'a',name:'Conta',type:'checking',openingBalance:NaN,openingDate:dateISO()}];assert.throws(()=>validateFinance(f));});
