'use client';

import {ArrowRight,CalendarDays,CheckCircle2,Info,Target,Wallet,AlertTriangle,ArrowDownLeft,ArrowUpRight,TrendingUp,Activity,Landmark} from 'lucide-react';
import {CATEGORIES,COLORS,dateISO} from '../lib/portfolio.mjs';
import {DEFAULT_FINANCE,summarizeFinance,upcomingFinanceObligations} from '../lib/finance.mjs';
import {confirmedFinanceInsights} from '../lib/insights.mjs';

const percent=value=>`${value.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const shortDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');

export function DashboardHome({state,calc,history,settings,personalReturn,period,onPeriod,display,hidden,Evolution,onNavigate,onClose}){
 const today=dateISO(),month=today.slice(0,7),finance=state.finance||DEFAULT_FINANCE(),summary=summarizeFinance(finance,month,today,state.events),obligations=upcomingFinanceObligations(finance,today,45),pending=finance.transactions.filter(t=>t.needsReview).length+(finance.pluggy?.review||[]).filter(r=>r.needsReview).length,insights=confirmedFinanceInsights(finance,today);
 const latestBalance=state.events.filter(e=>e.kind==='saldo').map(e=>e.date).sort().at(-1),balanceAge=latestBalance?Math.round((Date.parse(today)-Date.parse(latestBalance))/86400000):null;
 const investedThisMonth=state.events.filter(e=>e.kind==='aporte'&&e.date.startsWith(month)).reduce((n,e)=>n+e.amount,0),monthlyGap=Math.max(0,settings.monthly-investedThisMonth),wealthGoal=settings.wealthGoal||1000000,reserveGoal=settings.expenses*settings.reserveMonths;
 const categories=Object.entries(calc.byCategory||{}).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]);
 const topAssets=state.assets.filter(a=>a.id!=='cash').map(a=>({...a,value:calc.values[a.id]||0})).filter(a=>a.value>0).sort((a,b)=>b.value-a.value).slice(0,3);
 const attention=[
  pending>0&&{id:'review',title:`${pending} movimentação${pending===1?'':'ões'} para revisar`,detail:'Confirme categorias, duplicados e aportes sincronizados.',tab:'finance'},
  obligations.length>0&&{id:'due',title:`Próximo vencimento em ${shortDate(obligations[0].date)}`,detail:`${obligations[0].label} · ${display(obligations[0].amount)}`,tab:'finance'},
  balanceAge>45&&{id:'balance',title:'Atualize os saldos da carteira',detail:`Última conferência em ${shortDate(latestBalance)}.`,action:onClose},
  monthlyGap>0&&{id:'contribution',title:'Aporte mensal ainda não concluído',detail:`Faltam ${display(monthlyGap)} para a meta deste mês.`,tab:'plan'}
 ].filter(Boolean).slice(0,4);
 const visibleHistory=period==='all'?history:history.slice(-Number(period));
 const financeMetrics=[
  ['income','Recebido',summary.received,'Entradas confirmadas',ArrowDownLeft,'income'],
  ['expense','Pago',summary.paid,'Saídas da conta',ArrowUpRight,'paid'],
  ['investment','Aportes à carteira',summary.investments,'Inclui registros sem débito bancário',TrendingUp,'investment'],
  ['cashflow','Fluxo do mês',summary.netCashFlow,'Entradas − saídas',Activity,'cashflow']
 ];
 return <div className="home-dashboard">
  <div className="home-lead-grid">
   <section className="home-hero panel"><div className="home-hero-content"><span className="eyebrow">CARTEIRA CONJUNTA · PATRIMÔNIO INVESTIDO</span><h2>Seu patrimônio</h2><strong className="home-hero-value">{display(calc.total)}</strong><p>{latestBalance?`Saldos conferidos em ${shortDate(latestBalance)}`:`Carteira iniciada em ${shortDate(state.startDate)}`}. O saldo das contas bancárias aparece ao lado.</p><button className="secondary" onClick={()=>onNavigate('portfolio')}>Abrir carteira <ArrowRight size={16}/></button></div><div className="home-hero-results"><div><span>Resultado acumulado</span><strong className={calc.gain<0?'negative':''}>{display(calc.gain)}</strong><small>Após aportes e retiradas</small></div><div><span>Retorno pessoal (TIR)</span><strong>{personalReturn?percent(personalReturn.total*100):'—'}</strong><small>{personalReturn?'Considera as datas dos aportes':'Histórico insuficiente'}</small></div></div></section>
   <section className="home-month panel" aria-label="Resumo financeiro do mês"><div className="panel-heading"><div><span className="eyebrow">FINANÇAS · {new Date(`${month}-15T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).toUpperCase()}</span><h2>Seu mês financeiro</h2></div><button className="icon-button" aria-label="Abrir Finanças" onClick={()=>onNavigate('finance')}><ArrowRight size={19}/></button></div><button className="home-month-balance" onClick={()=>onNavigate('finance','accounts',{month})}><span><Landmark size={19}/>Disponível nas contas</span><strong className={summary.cash<0?'negative':''}>{display(summary.cash)}</strong><small>Saldo bancário · separado da carteira</small></button><div className="home-month-grid">{financeMetrics.map(([semantic,label,value,note,Icon,type])=><button key={label} className="home-month-metric" data-semantic={semantic} onClick={()=>onNavigate('finance','transactions',{month,type,status:'confirmed'})}><Icon size={18}/><span>{label}</span><strong className={value<0?'negative':''}>{display(value)}</strong><small>{note}</small></button>)}</div><div className="home-month-foot"><button onClick={()=>onNavigate('finance','transactions',{month,type:'spending',status:'confirmed'})}>Gastos por competência <strong>{display(summary.expenses)}</strong></button><button onClick={()=>onNavigate('finance','accounts',{month})}>Faturas a vencer no mês <strong>{display(summary.due)}</strong></button></div></section>
  </div>
  <div className="home-main-grid"><article className="panel home-evolution"><div className="panel-heading"><div><h2>Evolução do patrimônio</h2><p>Valor da carteira × capital investido</p></div><select aria-label="Período do gráfico" value={period} onChange={e=>onPeriod(e.target.value)}><option value="1">1 mês</option><option value="12">12 meses</option><option value="all">Histórico completo</option></select></div><Evolution data={visibleHistory} hidden={hidden}/><p className="muted small"><Info size={14}/> Meses sem saldo atualizado não representam cotação de mercado.</p></article><article className="panel home-attention"><div className="panel-heading"><div><h2>Próximas decisões</h2><p>Pendências e compromissos que pedem sua atenção.</p></div><CalendarDays size={19}/></div>{attention.length?<div className="home-attention-list">{attention.map(item=><button key={item.id} onClick={item.action||(()=>onNavigate(item.tab,item.id==='review'?'review':item.id==='due'?'scheduled':undefined))}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight size={17}/></button>)}</div>:<div className="home-clear"><CheckCircle2 size={21}/><span>Sem pendências ou vencimentos próximos cadastrados.</span></div>}{obligations.length>1&&<small className="muted">Mais {obligations.length-1} compromisso(s) nos próximos 45 dias.</small>}</article></div>
  <div className="home-support-grid"><article className="panel home-goals"><div className="panel-heading"><h2>Metas em andamento</h2><Target size={18}/></div>{[['Patrimônio investido',calc.total,wealthGoal],['Reserva',calc.reserve,reserveGoal],['Aporte do mês',investedThisMonth,settings.monthly]].map(([label,value,target])=><div className="home-goal" key={label}><div><strong>{label}</strong><span>{percent(target>0?Math.min(100,value/target*100):0)}</span></div><progress max={Math.max(target,1)} value={Math.max(0,Math.min(value,target))}/><small>{display(value)} de {display(target)}</small></div>)}<button className="text-button" onClick={()=>onNavigate('plan')}>Ver meu plano <ArrowRight size={15}/></button></article><article className="panel home-allocation"><div className="panel-heading"><h2>Onde está investido</h2><Wallet size={18}/></div>{categories.length?<><div className="home-allocation-track" role="img" aria-label="Distribuição da carteira por classe">{categories.map(([key,value])=><i key={key} style={{width:`${value/calc.total*100}%`,background:COLORS[key]||'var(--mint)'}}/>)}</div>{categories.map(([key,value])=><div className="home-allocation-row" key={key}><span><i style={{background:COLORS[key]||'var(--mint)'}}/>{CATEGORIES[key]||key}</span><strong>{percent(value/calc.total*100)}</strong></div>)}</>:<p className="muted">Registre um investimento para ver a alocação.</p>}<h3>Maiores posições</h3>{topAssets.map(asset=><div className="home-allocation-row" key={asset.id}><span>{asset.name}</span><strong>{display(asset.value)}</strong></div>)}<button className="text-button" onClick={()=>onNavigate('portfolio')}>Detalhar carteira <ArrowRight size={15}/></button></article><article className="panel home-insights"><div className="panel-heading"><div><h2>Alertas do mês</h2><p>Movimentações confirmadas.</p></div><AlertTriangle size={19}/></div>{insights.length?<div className="home-attention-list">{insights.slice(0,4).map(item=><button key={item.id} onClick={()=>onNavigate('finance')}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight size={17}/></button>)}</div>:<div className="home-clear"><CheckCircle2 size={20}/><span>Sem alertas de orçamento ou aumento relevante de gastos.</span></div>}<button className="text-button" onClick={()=>onNavigate('finance')}>Revisar lançamentos <ArrowRight size={15}/></button></article></div>
  <section className="home-secondary"><button className="secondary" onClick={()=>onNavigate('dividends')}>Dividendos <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onNavigate('analysis')}>Análise do mês <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onNavigate('history')}>Evolução mensal <ArrowRight size={15}/></button></section>
 </div>;
}
