'use client';

import {ArrowRight,CalendarDays,CheckCircle2,CreditCard,Info,Target,Wallet,AlertTriangle} from 'lucide-react';
import {CATEGORIES,COLORS,dateISO} from '../lib/portfolio.mjs';
import {DEFAULT_FINANCE,summarizeFinance,upcomingFinanceObligations} from '../lib/finance.mjs';
import {confirmedFinanceInsights} from '../lib/insights.mjs';

const percent=value=>`${value.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const shortDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');

export function DashboardHome({state,calc,history,settings,personalReturn,period,onPeriod,display,hidden,Evolution,onNavigate,onClose}){
 const today=dateISO(),month=today.slice(0,7),finance=state.finance||DEFAULT_FINANCE(),summary=summarizeFinance(finance,month,today),obligations=upcomingFinanceObligations(finance,today,45),pending=finance.transactions.filter(t=>t.needsReview).length+(finance.pluggy?.review||[]).filter(r=>r.needsReview).length,insights=confirmedFinanceInsights(finance,today);
 const latestBalance=state.events.filter(e=>e.kind==='saldo').map(e=>e.date).sort().at(-1),balanceAge=latestBalance?Math.round((Date.parse(today)-Date.parse(latestBalance))/86400000):null;
 const investedThisMonth=state.events.filter(e=>e.kind==='aporte'&&e.date.startsWith(month)).reduce((n,e)=>n+e.amount,0),monthlyGap=Math.max(0,settings.monthly-investedThisMonth),wealthGoal=settings.wealthGoal||1000000,reserveGoal=settings.expenses*settings.reserveMonths;
 const categories=Object.entries(calc.byCategory||{}).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]);
 const topAssets=state.assets.filter(a=>a.id!=='cash').map(a=>({...a,value:calc.values[a.id]||0})).filter(a=>a.value>0).sort((a,b)=>b.value-a.value).slice(0,3);
 const attention=[
  pending>0&&{id:'review',title:`${pending} movimentação${pending===1?'':'ões'} para revisar`,detail:'Confirme categorias, duplicados e aportes sincronizados.',tab:'finance'},
  obligations.length>0&&{id:'due',title:`Próximo vencimento em ${shortDate(obligations[0].date)}`,detail:`${obligations[0].label} · ${display(obligations[0].amount)}`,tab:'finance'},
  balanceAge>45&&{id:'balance',title:'Atualize os saldos da carteira',detail:`Última conferência em ${shortDate(latestBalance)}.`,action:onClose},
  monthlyGap>0&&{id:'contribution',title:'Aporte mensal ainda não concluído',detail:`Faltam ${display(monthlyGap)} para a meta deste mês.`,tab:'plan'}
 ].filter(Boolean).slice(0,4);
 const visibleHistory=period==='all'?history:history.slice(-Number(period));
 return <div className="home-dashboard">
  <section className="home-hero panel"><div><span className="eyebrow">CARTEIRA CONJUNTA</span><h2>Patrimônio investido</h2><strong className="home-hero-value">{display(calc.total)}</strong><p>Referência: {latestBalance?`saldos conferidos em ${shortDate(latestBalance)}`:`carteira iniciada em ${shortDate(state.startDate)}`}. Contas bancárias não entram neste valor.</p></div><div className="home-hero-results"><div><span>Resultado acumulado</span><strong className={calc.gain<0?'negative':''}>{display(calc.gain)}</strong><small>Aportes e retiradas descontados</small></div><div><span>Retorno pessoal</span><strong>{personalReturn?percent(personalReturn.total*100):'—'}</strong><small>{personalReturn?'Considera as datas dos aportes':'Histórico insuficiente'}</small></div><button className="secondary" onClick={()=>onNavigate('portfolio')}>Ver carteira <ArrowRight size={16}/></button></div></section>
  <section className="home-month panel" aria-label="Resumo do mês"><div className="panel-heading"><div><h2>Seu mês</h2><p>Gastos incluem compras no cartão; o caixa registra o pagamento da fatura.</p></div><button className="text-button" onClick={()=>onNavigate('finance')}>Abrir financeiro <ArrowRight size={15}/></button></div><div className="home-month-grid"><div><span>Receitas confirmadas</span><strong>{display(summary.income)}</strong></div><div><span>Gastos do mês</span><strong>{display(summary.expenses)}</strong></div><div><span>Aportes</span><strong>{display(summary.investments)}</strong></div><div><span>Fluxo de caixa confirmado</span><strong className={summary.netCashFlow<0?'negative':''}>{display(summary.netCashFlow)}</strong></div><div><span>Nas contas bancárias</span><strong>{display(summary.cash)}</strong></div></div></section>
  <section className="home-grid"><article className="panel home-attention"><div className="panel-heading"><div><h2>Precisa de atenção</h2><p>O que pode exigir uma decisão sua agora.</p></div><CalendarDays size={18}/></div>{attention.length?<div className="home-attention-list">{attention.map(item=><button key={item.id} onClick={item.action||(()=>onNavigate(item.tab))}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight size={17}/></button>)}</div>:<div className="home-clear"><CheckCircle2 size={21}/><span>Sem pendências ou vencimentos próximos cadastrados.</span></div>}{obligations.length>1&&<small className="muted">Mais {obligations.length-1} compromisso(s) nos próximos 45 dias no Controle financeiro.</small>}</article><article className="panel home-goals"><div className="panel-heading"><h2>Metas em andamento</h2><Target size={18}/></div>{[['Patrimônio investido',calc.total,wealthGoal],['Reserva',calc.reserve,reserveGoal],['Aporte do mês',investedThisMonth,settings.monthly]].map(([label,value,target])=><div className="home-goal" key={label}><div><strong>{label}</strong><span>{percent(target>0?Math.min(100,value/target*100):0)}</span></div><progress max={Math.max(target,1)} value={Math.max(0,Math.min(value,target))}/><small>{display(value)} de {display(target)}</small></div>)}<button className="text-button" onClick={()=>onNavigate('plan')}>Ver meu plano <ArrowRight size={15}/></button></article><article className="panel home-insights"><div className="panel-heading"><div><h2>Alertas do mês</h2><p>Só usamos movimentações confirmadas.</p></div><AlertTriangle size={19}/></div>{insights.length?<div className="home-attention-list">{insights.slice(0,4).map(item=><button key={item.id} onClick={()=>onNavigate('finance')}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight size={17}/></button>)}</div>:<div className="home-clear"><CheckCircle2 size={20}/><span>Sem alertas de orçamento ou aumento relevante de gastos.</span></div>}<button className="text-button" onClick={()=>onNavigate('finance')}>Revisar lançamentos <ArrowRight size={15}/></button></article></section>
  <section className="home-grid home-analysis"><article className="panel home-evolution"><div className="panel-heading"><div><h2>Evolução do patrimônio</h2><p>Valor da carteira × capital investido</p></div><select aria-label="Período do gráfico" value={period} onChange={e=>onPeriod(e.target.value)}><option value="1">1 mês</option><option value="12">12 meses</option><option value="all">Histórico completo</option></select></div><Evolution data={visibleHistory} hidden={hidden}/><p className="muted small"><Info size={14}/> Meses sem saldo atualizado não representam cotação de mercado.</p></article><article className="panel home-allocation"><div className="panel-heading"><h2>Onde está investido</h2><Wallet size={18}/></div>{categories.length?<><div className="home-allocation-track" role="img" aria-label="Distribuição da carteira por classe">{categories.map(([key,value])=><i key={key} style={{width:`${value/calc.total*100}%`,background:COLORS[key]||'var(--mint)'}}/>)}</div>{categories.slice(0,5).map(([key,value])=><div className="home-allocation-row" key={key}><span><i style={{background:COLORS[key]||'var(--mint)'}}/>{CATEGORIES[key]||key}</span><strong>{percent(value/calc.total*100)}</strong></div>)}</>:<p className="muted">Registre um investimento para ver a alocação.</p>}<h3>Maiores posições</h3>{topAssets.map(asset=><div className="home-allocation-row" key={asset.id}><span>{asset.name}</span><strong>{display(asset.value)}</strong></div>)}<button className="text-button" onClick={()=>onNavigate('portfolio')}>Detalhar carteira <ArrowRight size={15}/></button></article></section>
  <section className="home-secondary"><button className="secondary" onClick={()=>onNavigate('dividends')}>Dividendos <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onNavigate('analysis')}>Análise do mês <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onNavigate('history')}>Evolução mensal <ArrowRight size={15}/></button></section>
 </div>;
}
