'use client';
import {useEffect,useState} from 'react';
import {Moon,Sun} from 'lucide-react';
import {CATEGORIES,dateISO,rebalance} from '../lib/portfolio.mjs';

export function ThemeSwitch(){
 const [dark,setDark]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');let saved;try{saved=localStorage.getItem('patrimonio-theme')}catch{}const apply=value=>{setDark(value);document.documentElement.dataset.theme=value?'dark':'light'};apply(saved?saved==='dark':media.matches);const change=e=>{let preference;try{preference=localStorage.getItem('patrimonio-theme')}catch{}if(!preference)apply(e.matches)};media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 return <button className="icon-button" aria-label={dark?'Ativar tema claro':'Ativar tema escuro'} onClick={()=>{const value=!dark;setDark(value);document.documentElement.dataset.theme=value?'dark':'light';try{localStorage.setItem('patrimonio-theme',value?'dark':'light')}catch{}}}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button>;
}

export function AuthPanel({client,recovery,onRecovered}){
 const [mode,setMode]=useState('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const current=recovery?'password':mode;
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{let result;
  if(current==='password'){if(f.get('password')!==f.get('confirm'))throw new Error('As senhas precisam ser iguais.');result=await client.auth.updateUser({password:f.get('password')});}
  else if(current==='reset')result=await client.auth.resetPasswordForEmail(f.get('email'),{redirectTo:location.origin});
  else result=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});
  if(result.error)throw result.error;
  if(current==='password')onRecovered();else if(current==='reset')setMessage('Se o e-mail estiver cadastrado, você receberá um link para definir sua senha.');
 }catch(error){setMessage(error.message)}finally{setBusy(false)}}
 return <div className="auth-overlay"><form className="auth-card" onSubmit={submit}><h1>{current==='password'?'Defina sua senha':current==='reset'?'Recuperar acesso':'Patrimônio familiar'}</h1><p>Uma conta para vocês. A mesma carteira em todos os aparelhos.</p>{current!=='password'&&<label>Seu e-mail<input name="email" type="email" autoComplete="email" required/></label>}{current!=='reset'&&<label>{current==='password'?'Nova senha':'Senha'}<input name="password" type="password" autoComplete={current==='password'?'new-password':'current-password'} minLength={current==='password'?8:undefined} required/></label>}{current==='password'&&<label>Confirme a nova senha<input name="confirm" type="password" autoComplete="new-password" minLength={8} required/></label>}{message&&<p role="status" className="notice">{message}</p>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':current==='password'?'Salvar senha':current==='reset'?'Enviar link':'Entrar'}</button>{current!=='password'&&<button type="button" className="secondary full spaced" disabled={busy} onClick={()=>{setMode(mode==='login'?'reset':'login');setMessage('')}}>{mode==='login'?'Esqueci ou ainda não defini minha senha':'Voltar para o login'}</button>}<small>Acesso exclusivo para a conta já cadastrada.</small></form></div>;
}

export function PositionFields({asset}){return <><div className="form-grid"><label>Quantidade atual (opcional)<input name="quantity" type="number" min="0" step="any" defaultValue={asset?.quantity??''}/></label><label>Preço médio em reais (opcional)<input name="averagePrice" type="number" min="0" step="any" defaultValue={asset?.averagePrice??''}/></label><label>Data da compra (opcional)<input name="purchaseDate" type="date" max={dateISO()} defaultValue={asset?.purchaseDate||''}/></label><label>Instituição da posição<input name="institution" maxLength={80} placeholder="Ex.: Santander, corretora ou Tesouro Direto" defaultValue={asset?.institution||''}/></label><label>Responsável (opcional)<input name="owner" maxLength={60} placeholder="Lucas / esposa" defaultValue={asset?.owner||''}/></label></div><p className="muted small">A instituição organiza a alocação por local de custódia. Quantidade × preço médio informa o custo da posição; saldos e aportes continuam nos lançamentos.</p></>}
export function readPosition(f){return {quantity:f.get('quantity')===''?null:Number(f.get('quantity')),averagePrice:f.get('averagePrice')===''?null:Number(f.get('averagePrice')),purchaseDate:f.get('purchaseDate')||'',institution:String(f.get('institution')||'').trim(),owner:String(f.get('owner')||'').trim()}}

export function WealthGoal({state,calc,portfolioCalc=calc,display}){const target=state.settings.wealthGoal||1000000;return <section className="panel goal-panel spaced"><div><span className="eyebrow">META DE PATRIMÔNIO FAMILIAR</span><h2>{display(calc.total)} <span className="muted small">de {display(target)}</span></h2><p className="muted small">Capital familiar acumulado: {display(calc.netInvested)} · Aportes na carteira: {display(portfolioCalc.deposits)}</p></div><div><strong>{Math.min(100,calc.total/target*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%</strong><progress aria-label="Progresso da meta patrimonial" max={target} value={Math.max(0,calc.total)}/></div></section>}
export function Rebalance({state,display}){return <article className="panel table-wrap spaced"><h2>Distribuição atual e suas metas</h2><p className="muted small">Comparação com os percentuais que você definiu. Caixa de dividendos excluído; não é uma ordem de compra ou venda.</p><table><thead><tr><th>Classe</th><th>Atual</th><th>Meta</th><th>Diferença para a meta</th></tr></thead><tbody>{rebalance(state).map(r=><tr key={r.key}><td>{CATEGORIES[r.key]}</td><td>{r.current.toFixed(1)}%</td><td>{r.target}%</td><td>{r.gap>0?'Faltam ':r.gap<0?'Acima em ':''}{display(Math.abs(r.gap))}</td></tr>)}</tbody></table></article>}
