'use client';
import {useEffect,useState} from 'react';
import {Moon,Sun} from 'lucide-react';
import {CATEGORIES,dateISO,rebalance} from '../lib/portfolio.mjs';

export function ThemeSwitch(){
 const [dark,setDark]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');let saved;try{saved=localStorage.getItem('patrimonio-theme')}catch{}const apply=value=>{setDark(value);document.documentElement.dataset.theme=value?'dark':'light'};apply(saved?saved==='dark':media.matches);const change=e=>{let preference;try{preference=localStorage.getItem('patrimonio-theme')}catch{}if(!preference)apply(e.matches)};media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 return <button className="icon-button" aria-label={dark?'Ativar tema claro':'Ativar tema escuro'} onClick={()=>{const value=!dark;setDark(value);document.documentElement.dataset.theme=value?'dark':'light';try{localStorage.setItem('patrimonio-theme',value?'dark':'light')}catch{}}}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button>;
}

export function AuthPanel({client,recovery,onRecovered}){
 const [mode,setMode]=useState('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const current=recovery?'password':mode;
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{let result;
  if(current==='password'){if(f.get('password')!==f.get('confirm'))throw new Error('As senhas precisam ser iguais.');result=await client.auth.updateUser({password:f.get('password')});}
  else if(current==='reset')result=await client.auth.resetPasswordForEmail(f.get('email'),{redirectTo:location.origin});
  else result=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});
  if(result.error)throw result.error;
  if(current==='password')onRecovered();else if(current==='reset')setMessage('Se o e-mail estiver cadastrado, você receberá um link para definir sua senha.');
 }catch(error){setMessage(error.message)}finally{setBusy(false)}}
 return <div className="auth-overlay"><form className="auth-card" onSubmit={submit}><h1>{current==='password'?'Defina sua senha':current==='reset'?'Recuperar acesso':'Patrimônio familiar'}</h1><p>Uma conta para vocês. A mesma carteira em todos os aparelhos.</p>{current!=='password'&&<label>Seu e-mail<input name="email" type="email" autoComplete="email" required/></label>}{current!=='reset'&&<label>{current==='password'?'Nova senha':'Senha'}<input name="password" type="password" autoComplete={current==='password'?'new-password':'current-password'} minLength={current==='password'?8:undefined} required/></label>}{current==='password'&&<label>Confirme a nova senha<input name="confirm" type="password" autoComplete="new-password" minLength={8} required/></label>}{message&&<p role="status" className="notice">{message}</p>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':current==='password'?'Salvar senha':current==='reset'?'Enviar link':'Entrar'}</button>{current!=='password'&&<button type="button" className="secondary full spaced" disabled={busy} onClick={()=>{setMode(mode==='login'?'reset':'login');setMessage('')}}>{mode==='login'?'Esqueci ou ainda não defini minha senha':'Voltar para o login'}</button>}<small>Acesso exclusivo para a conta já cadastrada.</small></form></div>;
}

export function PositionFields({asset}){return <><div className="form-grid"><label>Quantidade atual (opcional)<input name="quantity" type="number" min="0" step="any" defaultValue={asset?.quantity??''}/></label><label>Preço médio em reais (opcional)<input name="averagePrice" type="number" min="0" step="any" defaultValue={asset?.averagePrice??''}/></label><label>Data da compra (opcional)<input name="purchaseDate" type="date" max={dateISO()} defaultValue={asset?.purchaseDate||''}/></label><label>Responsável (opcional)<input name="owner" maxLength={60} placeholder="Lucas / esposa" defaultValue={asset?.owner||''}/></label></div><p className="muted small">Quantidade × preço médio informa o custo da posição. Atualize esses campos após compras ou vendas. Os saldos e aportes continuam sendo registrados nos lançamentos.</p></>}
export function readPosition(f){return {quantity:f.get('quantity')===''?null:Number(f.get('quantity')),averagePrice:f.get('averagePrice')===''?null:Number(f.get('averagePrice')),purchaseDate:f.get('purchaseDate')||'',owner:String(f.get('owner')||'').trim()}}

export function WealthGoal({state,calc,display}){const target=state.settings.wealthGoal||1000000;return <section className="panel goal-panel spaced"><div><span className="eyebrow">META DE PATRIMÔNIO</span><h2>{display(calc.total)} <span className="muted small">de {display(target)}</span></h2><p className="muted small">Capital investido líquido: {display(calc.netInvested)} · Aportes registrados: {display(calc.deposits)}</p></div><div><strong>{Math.min(100,calc.total/target*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%</strong><progress aria-label="Progresso da meta patrimonial" max={target} value={Math.max(0,calc.total)}/></div></section>}
export function Rebalance({state,display}){return <article className="panel table-wrap spaced"><h2>Distribuição atual e suas metas</h2><p className="muted small">Comparação com os percentuais que você definiu. Caixa de dividendos excluído; não é uma ordem de compra ou venda.</p><table><thead><tr><th>Classe</th><th>Atual</th><th>Meta</th><th>Diferença para a meta</th></tr></thead><tbody>{rebalance(state).map(r=><tr key={r.key}><td>{CATEGORIES[r.key]}</td><td>{r.current.toFixed(1)}%</td><td>{r.target}%</td><td>{r.gap>0?'Faltam ':r.gap<0?'Acima em ':''}{display(Math.abs(r.gap))}</td></tr>)}</tbody></table></article>}

export function Journal({state,onSave,busy,display}){
 const [editing,setEditing]=useState(null),[formKey,setFormKey]=useState(0),[removing,setRemoving]=useState(null);
 const entries=state.journal||[];
 return <><form key={editing?.id||formKey} className="panel" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={id:editing?.id||crypto.randomUUID(),date:f.get('date'),ticker:String(f.get('ticker')).trim().toUpperCase(),amount:Number(f.get('amount')),reason:String(f.get('reason')).trim(),expectation:String(f.get('expectation')),notes:String(f.get('notes'))};const ok=await onSave({...state,journal:editing?.id?entries.map(x=>x.id===item.id?item:x):[...entries,item]},'Registro salvo no diário.');if(ok){setEditing(null);setFormKey(k=>k+1);}}}><h2>{editing?'Revisar registro':'Diário do investidor'}</h2><p className="muted">Registre sua decisão e depois compare a expectativa com o que aconteceu. O diário não movimenta os saldos da carteira.</p><div className="form-grid"><label>Ativo<input name="ticker" maxLength={12} defaultValue={editing?.ticker||''} required/></label><label>Data<input name="date" type="date" max={dateISO()} defaultValue={editing?.date||dateISO()} required/></label><label>Valor da decisão (R$)<input name="amount" type="number" min="0" step=".01" defaultValue={editing?.amount??0} required/></label></div><label>Por que comprei ou pretendo comprar?<textarea name="reason" maxLength={2000} defaultValue={editing?.reason||''} required/></label><label>Minha expectativa<textarea name="expectation" maxLength={2000} defaultValue={editing?.expectation||''}/></label><label>Observações e revisão<textarea name="notes" maxLength={2000} defaultValue={editing?.notes||''}/></label><div className="button-row"><button className="primary" disabled={busy}>Salvar no diário</button><button type="button" className="secondary" onClick={()=>(setEditing(null),setFormKey(k=>k+1))}>Limpar formulário</button></div></form><section className="two-cols spaced">{[...entries].sort((a,b)=>b.date.localeCompare(a.date)).map(e=><article className="panel journal-entry" key={e.id}><span className="eyebrow">{e.date} · {display(e.amount)}</span><h2>{e.ticker}</h2><p>{e.reason}</p>{e.expectation&&<p><b>Expectativa:</b> {e.expectation}</p>}{e.notes&&<p><b>Revisão:</b> {e.notes}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>{setEditing(e);window.scrollTo({top:0,behavior:'smooth'})}}>Editar</button><button className="secondary" disabled={busy} onClick={()=>setRemoving(e.id)}>Excluir</button></div>{removing===e.id&&<div className="notice"><span>Excluir este registro?</span><button className="danger-button" disabled={busy} onClick={async()=>{const ok=await onSave({...state,journal:entries.filter(x=>x.id!==e.id)},'Registro excluído.');if(ok){setRemoving(null);if(editing?.id===e.id)setEditing(null)}}}>Confirmar</button><button className="secondary" onClick={()=>setRemoving(null)}>Cancelar</button></div>}</article>)}</section>{!entries.length&&<p className="muted spaced">Nenhuma decisão registrada ainda.</p>}</>;
}
