'use client';
import {useEffect,useState} from 'react';
import {Moon,Sun,Calculator,Target} from 'lucide-react';
import {CATEGORIES,COLORS,dateISO} from '../lib/portfolio.mjs';
import {simulateContribution,monthContributionProgress} from '../lib/investment-simulation.mjs';

export function ThemeSwitch(){
 const [dark,setDark]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>{let saved;try{saved=localStorage.getItem('patrimonio-theme')}catch{}const next=saved==='dark'||(saved!=='light'&&media.matches);document.documentElement.dataset.theme=next?'dark':'light';setDark(next)};apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply)},[]);
 const toggle=()=>{const next=!dark;document.documentElement.dataset.theme=next?'dark':'light';setDark(next);try{localStorage.setItem('patrimonio-theme',next?'dark':'light')}catch{}};
 return <button type="button" className="icon-button theme-toggle" aria-label={dark?'Mudar para tema claro':'Mudar para tema escuro'} title={dark?'Tema escuro · alternar para claro':'Tema claro · alternar para escuro'} aria-pressed={dark} onClick={toggle}>{dark?<Sun size={18} aria-hidden="true"/>:<Moon size={18} aria-hidden="true"/>}</button>;
}

export function AuthPanel({client,recovery,onRecovered}){
 const [mode,setMode]=useState('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const current=recovery?'password':mode;
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{let result;
  if(current==='password'){if(f.get('password')!==f.get('confirm'))throw new Error('As senhas precisam ser iguais.');result=await client.auth.updateUser({password:f.get('password')});}
  else if(current==='reset')result=await client.auth.resetPasswordForEmail(f.get('email'),{redirectTo:location.origin});
  else result=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});
  if(result.error)throw result.error;
  if(current==='password')onRecovered();else if(current==='reset')setMessage('Se o e-mail estiver cadastrado, você receberá um link para definir sua senha.');
 }catch(error){setMessage(error.message)}finally{setBusy(false)}}
 return <div className="auth-overlay"><form className="auth-card" onSubmit={submit}><h1>{current==='password'?'Defina sua senha':current==='reset'?'Recuperar acesso':'Patrimônio familiar'}</h1><p>Uma conta para vocês. A mesma carteira em todos os aparelhos.</p>{current!=='password'&&<label>Seu e-mail<input name="email" type="email" autoComplete="email" required/></label>}{current!=='reset'&&<label>{current==='password'?'Nova senha':'Senha'}<input name="password" type="password" autoComplete={current==='password'?'new-password':'current-password'} minLength={current==='password'?8:undefined} required/></label>}{current==='password'&&<label>Confirme a nova senha<input name="confirm" type="password" autoComplete="new-password" minLength={8} required/></label>}{message&&<p role="status" className="notice">{message}</p>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':current==='password'?'Salvar senha':current==='reset'?'Enviar link':'Entrar'}</button>{current!=='password'&&<button type="button" className="secondary full spaced" disabled={busy} onClick={()=>{setMode(mode==='login'?'reset':'login');setMessage('')}}>{mode==='login'?'Esqueci ou ainda não defini minha senha':'Voltar para o login'}</button>}<small>Acesso exclusivo para a conta já cadastrada.</small></form></div>;
}

export function PositionFields({asset}){return <><div className="form-grid"><label>Quantidade atual (opcional)<input name="quantity" type="number" min="0" step="any" defaultValue={asset?.quantity??''}/></label><label>Preço médio em reais (opcional)<input name="averagePrice" type="number" min="0" step="any" defaultValue={asset?.averagePrice??''}/></label><label>Data da compra (opcional)<input name="purchaseDate" type="date" max={dateISO()} defaultValue={asset?.purchaseDate||''}/></label><label>Instituição da posição<input name="institution" maxLength={80} placeholder="Ex.: Santander, corretora ou Tesouro Direto" defaultValue={asset?.institution||''}/></label><label>Responsável (opcional)<input name="owner" maxLength={60} placeholder="Lucas / esposa" defaultValue={asset?.owner||''}/></label></div><p className="muted small">A instituição organiza a alocação por local de custódia. Quantidade × preço médio informa o custo da posição; saldos e aportes continuam nos lançamentos.</p></>}
export function readPosition(f){return {quantity:f.get('quantity')===''?null:Number(f.get('quantity')),averagePrice:f.get('averagePrice')===''?null:Number(f.get('averagePrice')),purchaseDate:f.get('purchaseDate')||'',institution:String(f.get('institution')||'').trim(),owner:String(f.get('owner')||'').trim()}}

export function WealthGoal({state,calc,portfolioCalc=calc,display}){const target=state.settings.wealthGoal||1000000;return <section className="panel goal-panel spaced"><div><span className="eyebrow">META DE PATRIMÔNIO FAMILIAR</span><h2>{display(calc.total)} <span className="muted small">de {display(target)}</span></h2><p className="muted small">Capital familiar acumulado: {display(calc.netInvested)} · Aportes na carteira: {display(portfolioCalc.deposits)}</p></div><div><strong>{Math.min(100,calc.total/target*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%</strong><progress aria-label="Progresso da meta patrimonial" max={target} value={Math.max(0,calc.total)}/></div></section>}
export function Rebalance({state,display}){
 const [amount,setAmount]=useState(String(state.settings.monthly)),progress=monthContributionProgress(state),validAmount=amount!==''&&Number.isFinite(Number(amount))&&Number(amount)>=0&&Number(amount)<=1e12;
 const rows=simulateContribution(state,validAmount?Number(amount):0),activeRows=rows.filter(row=>row.target>0||row.value>0);
 return <article className="panel rebalance-panel spaced"><div className="panel-heading"><div><span className="eyebrow">PRÓXIMO APORTE</span><h2>Simule sua distribuição</h2><p>Uma simulação pelos percentuais que você definiu, sem movimentar a carteira.</p></div><Calculator size={23} aria-hidden="true"/></div>
  <div className="rebalance-inputs"><label>Valor para simular (R$)<input type="number" min="0" max="1000000000000" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} aria-describedby="rebalance-explanation"/></label><div className="rebalance-presets"><button type="button" className="secondary" onClick={()=>setAmount(String(progress.goal))}><Target size={15}/>Meta mensal <b>{display(progress.goal)}</b></button><button type="button" className="secondary" onClick={()=>setAmount(String(progress.remaining))}>Restante do mês <b>{display(progress.remaining)}</b></button></div></div>
  <p className="small muted" id="rebalance-explanation">Já aportado neste mês: <strong>{display(progress.deposited)}</strong>. Caixa de dividendos fica fora da distribuição. Os valores simulados priorizam classes abaixo da sua meta.</p>
  {!validAmount&&<p role="status" className="negative small">Informe um valor válido para simular.</p>}
  <div className="rebalance-rows">{activeRows.map(row=><div className="rebalance-row" key={row.key} style={{'--asset-color':COLORS[row.key]}}><div className="rebalance-class"><i/><strong>{CATEGORIES[row.key]}</strong><span>Meta {row.target}%</span></div><div className="rebalance-progress"><div className="rebalance-track" role="img" aria-label={`Atual ${row.current.toFixed(1)}%, após simulação ${row.after.toFixed(1)}%, meta ${row.target}%`}><i style={{width:`${Math.min(100,row.current)}%`}}/><b style={{left:`${Math.min(100,row.target)}%`}}/></div><span>Atual {row.current.toLocaleString('pt-BR',{maximumFractionDigits:1})}% <span aria-hidden="true">→</span> Depois {row.after.toLocaleString('pt-BR',{maximumFractionDigits:1})}%</span></div><div className="rebalance-amount"><small>Aporte simulado</small><strong>{display(row.suggested)}</strong></div></div>)}</div>
  <div className="rebalance-total"><span>Total distribuído</span><strong>{display(rows.reduce((sum,row)=>sum+row.suggested,0))}</strong></div>
 </article>;
}
