'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowLeft,ArrowRight,ArrowUpRight,CalendarDays,Check,CreditCard,Download,Plus,ReceiptText,Repeat,Trash2,Upload,Wallet} from 'lucide-react';
import {DEFAULT_FINANCE,FINANCE_CATEGORIES,accountBalances,addMonthlyRecurring,csvFingerprint,importPreviewRows,installmentSchedule,invoiceSummaries,monthEnd,monthOf,parseStatementCsv,shiftMonth,summarizeFinance} from '../lib/finance.mjs';
import {money,dateISO,moneyWeightedReturn,periodStartDate} from '../lib/portfolio.mjs';
import {supabase} from '../lib/supabase';
import {mergePluggyData} from '../lib/pluggy-sync.mjs';

const todayMonth=()=>dateISO().slice(0,7);
const FINANCE_HISTORY_START='2026-08-01';
const fmtDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR');
const fmtMonth=m=>new Date(`${m}-15T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
const monthOptions=(first,last)=>{const out=[];for(let m=first;m<=last;m=shiftMonth(m,1))out.push(m);return out;};
const empty=f=>f||DEFAULT_FINANCE();
const TYPES={income:'Receita',expense:'Despesa à vista',transfer:'Transferência',investment:'Aporte em investimento',card_purchase:'Compra no cartão',card_payment:'Pagamento de fatura'};
const SECTIONS=[['overview','Visão geral'],['transactions','Lançamentos'],['budget','Orçamento'],['cards','Cartões e faturas'],['accounts','Contas'],['import','Importação']];
function Card({title,children,icon:Icon=Wallet}){return <article className="panel finance-card"><div className="panel-heading"><h2>{title}</h2><Icon size={19}/></div>{children}</article>}
function Stats({summary,display}){const items=[['Receitas',summary.income],['Despesas',summary.expenses],['Aportes',summary.investments],['Fluxo do mês',summary.netCashFlow],['Saldo disponível',summary.cash],['Faturas a vencer',summary.due]];return <section className="finance-stats">{items.map(([label,value])=><article className="panel" key={label}><span>{label}</span><strong className={label==='Fluxo do mês'&&value<0?'negative':''}>{display(value)}</strong></article>)}</section>}
export function FinanceDashboard({finance,month,display,onOpen}){const f=empty(finance),s=summarizeFinance(f,month);return <section className="finance-dashboard panel spaced"><div className="panel-heading"><div><h2>Seu mês financeiro</h2><p>Entradas, despesas e faturas; o saldo bancário fica fora do patrimônio investido.</p></div><button className="text-button" onClick={onOpen}>Abrir controle financeiro <ArrowUpRight size={16}/></button></div><div className="finance-summary-grid"><div><span>Disponível nas contas</span><strong>{display(s.cash)}</strong></div><div><span>Despesas do mês (cartão incluído)</span><strong>{display(s.expenses)}</strong></div><div><span>Faturas a vencer neste mês</span><strong>{display(s.due)}</strong></div></div></section>}

export function Finance({state,onSave,display,notify}){
 const finance=empty(state.finance),[month,setMonth]=useState(todayMonth),[section,setSection]=useState('overview'),[type,setType]=useState('expense'),[csvRows,setCsvRows]=useState(null),[csvAccount,setCsvAccount]=useState(''),[csvCategory,setCsvCategory]=useState('Outros'),[budgetValues,setBudgetValues]=useState({}),[showAccount,setShowAccount]=useState(false),[showCard,setShowCard]=useState(false),[busy,setBusy]=useState(false),[period,setPeriod]=useState('12'),[benchmark,setBenchmark]=useState(null),[benchmarkLoading,setBenchmarkLoading]=useState(false),[filterType,setFilterType]=useState('all'),[filterCategory,setFilterCategory]=useState('all'),[filterAccount,setFilterAccount]=useState('all'),[search,setSearch]=useState(''),[pluggyItemId,setPluggyItemId]=useState(finance.pluggy?.itemId||'');
 const csvRef=useRef(null),categories=useMemo(()=>[...new Set([...FINANCE_CATEGORIES,...(finance.categories||[])])],[finance.categories]),asOf=monthEnd(month),summary=summarizeFinance(finance,month,asOf),today=todayMonth(),minMonth=FINANCE_HISTORY_START.slice(0,7),balances=accountBalances(finance,asOf),invoices=summary.invoices;
 useEffect(()=>setBudgetValues(finance.budgets[month]||{}),[finance.budgets,month]);
 const commit=async(next,message,events=state.events)=>{setBusy(true);try{return await onSave({...state,events,finance:next},message)!==false;}finally{setBusy(false);}};
 const savePluggyItem=async e=>{e.preventDefault();const next=structuredClone(finance);next.pluggy={...(next.pluggy||{}),itemId:pluggyItemId.trim()};await commit(next,'Item ID do Meu Pluggy salvo com segurança na sua carteira privada.');};
 const syncPluggy=async()=>{if(!finance.pluggy?.itemId)return notify('Salve primeiro o Item ID do Meu Pluggy.');if(!supabase)return notify('A integração Pluggy requer a versão publicada com Supabase.');setBusy(true);try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Entre na sua conta antes de sincronizar.');const response=await fetch('/api/pluggy/sync',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({itemId:finance.pluggy.itemId,startDate:FINANCE_HISTORY_START})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Falha ao consultar Meu Pluggy.');const merged=mergePluggyData(state,payload);const next=merged.finance;if(await commit(next,`${merged.imported} novas movimentações importadas desde agosto.${merged.skippedAccounts?` ${merged.skippedAccounts} contas de cartão/investimento foram ignoradas para evitar contabilização incorreta.`:''}`))notify(`Sincronização concluída: ${merged.imported} novas movimentações desde agosto.${merged.skippedAccounts?` ${merged.skippedAccounts} contas não bancárias foram ignoradas.`:''}`);}catch(error){notify(error.message);}finally{setBusy(false);}};
 const addAccount=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),next=structuredClone(finance);next.accounts.push({id:crypto.randomUUID(),name:String(d.get('name')).trim(),type:String(d.get('type')),openingBalance:Number(d.get('openingBalance')||0),openingDate:String(d.get('openingDate'))});if(await commit(next,'Conta adicionada.')){form.reset();setShowAccount(false);}};
 const deleteAccount=async account=>{const linked=finance.transactions.filter(t=>t.accountId===account.id||t.toAccountId===account.id);const linkedCards=finance.cards.filter(c=>c.accountId===account.id);if(linkedCards.length)return notify('Antes de excluir esta conta, remova ou associe seus cartões a outra conta.');if(!confirm(`Excluir “${account.name}” e seus ${linked.length} lançamentos associados? Esta ação não pode ser desfeita.`))return;const next=structuredClone(finance);next.accounts=next.accounts.filter(a=>a.id!==account.id);next.transactions=next.transactions.filter(t=>t.accountId!==account.id&&t.toAccountId!==account.id);next.recurring=next.recurring.filter(r=>r.accountId!==account.id);await commit(next,'Conta e lançamentos associados excluídos.');};
 const addCard=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),next=structuredClone(finance);next.cards.push({id:crypto.randomUUID(),name:String(d.get('name')).trim(),accountId:String(d.get('accountId')),closeDay:Number(d.get('closeDay')),dueDay:Number(d.get('dueDay'))});if(await commit(next,'Cartão adicionado.')){form.reset();setShowCard(false);}};
 const addTransaction=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),kind=String(d.get('type')),amount=Number(d.get('amount')),date=String(d.get('date')),description=String(d.get('description')).trim(),category=String(d.get('category')||'Outros'),next=structuredClone(finance);let eventsNext=state.events;const tx={id:crypto.randomUUID(),type:kind,amount,date,description,category};
  if(['income','expense','transfer','investment'].includes(kind))tx.accountId=String(d.get('accountId'));
  if(kind==='transfer'){tx.toAccountId=String(d.get('toAccountId'));if(tx.accountId===tx.toAccountId)return notify('Escolha contas diferentes para a transferência.');}
  if(kind==='investment'){tx.assetId=String(d.get('assetId'));const event={id:crypto.randomUUID(),date,kind:'aporte',assetId:tx.assetId,amount,note:`Aporte via ${finance.accounts.find(a=>a.id===tx.accountId)?.name||'conta'}: ${description}`,createdAt:new Date().toISOString()};tx.portfolioEventId=event.id;eventsNext=[...state.events,event];}
  if(kind==='card_purchase'){tx.cardId=String(d.get('cardId'));tx.installments=Number(d.get('installments'));const card=finance.cards.find(c=>c.id===tx.cardId);tx.closeDay=card.closeDay;tx.dueDay=card.dueDay;tx.installmentParts=installmentSchedule({date,amount,installments:tx.installments,closeDay:card.closeDay,dueDay:card.dueDay});tx.invoiceMonth=tx.installmentParts[0].invoiceMonth;tx.dueDate=tx.installmentParts[0].dueDate;}
  if(kind==='card_payment'){const [cardId,invoiceMonth]=String(d.get('invoiceKey')).split('|');tx.cardId=cardId;tx.accountId=finance.cards.find(c=>c.id===cardId)?.accountId;tx.invoiceMonth=invoiceMonth;const due=invoiceSummaries(finance,asOf).find(i=>i.cardId===cardId&&i.invoiceMonth===invoiceMonth);if(!due||amount>due.open+.005)return notify('O pagamento não pode ser maior que o saldo aberto dessa fatura.');}
  if(d.get('recurring')==='on'&&['income','expense'].includes(kind)){const recurringId=crypto.randomUUID();tx.recurringId=recurringId;next.recurring.push({id:recurringId,type:kind,accountId:tx.accountId,amount,description,category,day:Number(date.slice(8,10))});}
  next.transactions.push(tx);if(await commit(next,kind==='investment'?'Aporte registrado e vinculado à carteira.':'Lançamento financeiro salvo.',eventsNext))form.reset();};
 const deleteTransaction=async tx=>{if(!confirm('Excluir este lançamento?'))return;const next=structuredClone(finance);next.transactions=next.transactions.filter(t=>t.id!==tx.id);if(tx.recurringId&&!next.transactions.some(t=>t.recurringId===tx.recurringId))next.recurring=next.recurring.filter(r=>r.id!==tx.recurringId);if(tx.type==='investment'){await onSave({...state,events:state.events.filter(e=>e.id!==tx.portfolioEventId),finance:next},'Lançamento e aporte removidos.');return;}await commit(next,'Lançamento removido.');};
 const loadCsv=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const rows=parseStatementCsv(await file.text(),FINANCE_HISTORY_START);setCsvRows(importPreviewRows(rows,finance.transactions));setCsvAccount(finance.accounts[0]?.id||'');notify(`${rows.length} linhas encontradas. Revise antes de importar.`);}catch(err){notify(err.message);}};
 const exportFinanceCsv=()=>{const labels={income:'Receita',expense:'Despesa',transfer:'Transferência',investment:'Aporte',card_purchase:'Compra no cartão',card_payment:'Pagamento de fatura'},escape=value=>`"${String(value??'').replace(/"/g,'""')}"`,rows=[['Data','Tipo','Descrição','Categoria','Valor (R$)','Conta/cartão','Fatura'],...finance.transactions.map(t=>[t.date,labels[t.type],t.description,t.category||'',t.amount.toFixed(2).replace('.',','),finance.accounts.find(a=>a.id===t.accountId)?.name||finance.cards.find(c=>c.id===t.cardId)?.name||'',t.invoiceMonth||''])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`controle-financeiro-${dateISO()}.csv`;a.click();URL.revokeObjectURL(url);};
 const importCsv=async()=>{if(!csvAccount)return notify('Cadastre ou selecione uma conta antes da importação.');const selected=csvRows.filter(r=>r.selected&&!r.duplicate);if(!selected.length)return notify('Não há linhas novas selecionadas para importar.');const next=structuredClone(finance);next.transactions.push(...selected.map(r=>({id:crypto.randomUUID(),type:r.type,accountId:csvAccount,amount:r.amount,date:r.date,description:r.description,category:r.category||csvCategory,importFingerprint:csvFingerprint(r)})));if(await commit(next,`${selected.length} lançamentos importados.`))setCsvRows(null);};
 const saveBudget=async e=>{e.preventDefault();const next=structuredClone(finance);next.budgets[month]=Object.fromEntries(categories.map(c=>[c,Number(budgetValues[c]||0)]));await commit(next,`Orçamento de ${fmtMonth(month)} salvo.`);};
 const addCategory=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),name=String(d.get('category')).trim().slice(0,60);if(!name)return;const next=structuredClone(finance);next.categories=[...new Set([...(next.categories||[]),name])];if(await commit(next,'Categoria criada.'))form.reset();};
 const addRecurring=async()=>{const result=addMonthlyRecurring(finance,month);if(!result.added)return notify('As despesas recorrentes deste mês já foram lançadas.');await commit(result.finance,`${result.added} lançamento(s) recorrente(s) adicionados.`);};
 const runBenchmarks=async selected=>{setPeriod(selected);setBenchmarkLoading(true);try{const startDate=periodStartDate(state,selected),response=await fetch(`/api/benchmarks?period=${selected}&startDate=${startDate}`),data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível carregar as referências.');setBenchmark(data);}catch(e){setBenchmark({error:e.message,results:[]});}finally{setBenchmarkLoading(false);}};
 const moveMonth=offset=>{const target=shiftMonth(month,offset);if(target>=minMonth&&target<=today)setMonth(target);};
 const selectedDate=month===today?dateISO():`${month}-01`,personalReturn=moneyWeightedReturn(state,periodStartDate(state,period)),monthTransactions=finance.transactions.filter(t=>monthOf(t.date)===month),visibleTransactions=monthTransactions.filter(t=>{const accountId=t.accountId||finance.cards.find(c=>c.id===t.cardId)?.accountId;return(filterType==='all'||t.type===filterType)&&(filterCategory==='all'||(t.category||'Outros')===filterCategory)&&(filterAccount==='all'||accountId===filterAccount)&&(!search||`${t.description} ${t.category||''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));}).sort((a,b)=>b.date.localeCompare(a.date)),monthInvoices=invoices.filter(i=>i.invoiceMonth===month);
 return <div className="finance-page">
  <div className="finance-monthbar"><div><span className="eyebrow">COMPETÊNCIA</span><h2>{fmtMonth(month)}</h2></div><div className="finance-month-controls"><button className="secondary icon-button" aria-label="Mês anterior" disabled={month<=minMonth} onClick={()=>moveMonth(-1)}><ArrowLeft size={17}/></button><label className="sr-only" htmlFor="finance-month">Selecionar mês</label><select id="finance-month" aria-label="Selecionar mês" value={month} onChange={e=>setMonth(e.target.value)}>{monthOptions(minMonth,today).reverse().map(m=><option key={m} value={m}>{fmtMonth(m)}</option>)}</select><button className="secondary icon-button" aria-label="Próximo mês" disabled={month>=today} onClick={()=>moveMonth(1)}><ArrowRight size={17}/></button></div></div>
  <Stats summary={summary} display={display}/>
  <nav className="finance-sections" aria-label="Seções do controle financeiro">{SECTIONS.map(([id,label])=><button key={id} className={section===id?'active':''} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}>{label}</button>)}</nav>
  {section==='overview'&&<>
   <section className="two-cols spaced"><Card title="Saldo disponível nas contas"><div className="finance-list">{finance.accounts.map(a=><div className="finance-row" key={a.id}><span className="finance-row-icon"><Wallet size={17}/></span><span><strong>{a.name}</strong><small>{a.type==='checking'?'Conta corrente':a.type==='savings'?'Poupança':'Dinheiro'}</small></span><strong>{display(summary.balances[a.id]||0)}</strong></div>)}</div>{!finance.accounts.length&&<p className="muted">Cadastre uma conta para acompanhar o saldo disponível.</p>}<button className="text-button" onClick={()=>setSection('accounts')}>Gerenciar contas <ArrowRight size={15}/></button></Card>
    <Card title="Faturas do mês" icon={CreditCard}><div className="finance-list">{monthInvoices.filter(i=>i.open>0).map(i=><div className="finance-row" key={`${i.cardId}-${i.invoiceMonth}`}><span className="finance-row-icon"><CreditCard size={17}/></span><span><strong>{i.cardName}</strong><small>Vence {fmtDate(i.dueDate)} · pago {display(i.paid)}</small></span><strong>{display(i.open)}</strong></div>)}</div>{!monthInvoices.length&&<p className="muted">Nenhuma fatura de cartão neste mês.</p>}<button className="text-button" onClick={()=>setSection('cards')}>Ver cartões e faturas <ArrowRight size={15}/></button></Card>
   </section>
   <Card title="Orçamento por categoria" icon={CalendarDays}><div className="finance-budget-summary">{categories.map(c=>{const spent=summary.expensesByCategory[c]||0,limit=Number(summary.budget[c]||0);if(!spent&&!limit)return null;return <div className="finance-budget-item" key={c}><span>{c}</span><strong>{display(spent)}{limit?` / ${display(limit)}`:''}</strong>{limit>0&&<i style={{'--budget-progress':`${Math.min(100,spent/limit*100)}%`}}/>}</div>})}</div>{!Object.keys(summary.budget).length&&!Object.keys(summary.expensesByCategory).length&&<p className="muted">Defina limites e acompanhe seus gastos nesta competência.</p>}<button className="text-button" onClick={()=>setSection('budget')}>Abrir orçamento <ArrowRight size={15}/></button></Card>
   <Card title="Comparação de rendimento"><p className="muted">Rentabilidade da carteira em comparação com CDI, IPCA e Ibovespa.</p><div className="button-row"><label>Período<select value={period} onChange={e=>runBenchmarks(e.target.value)}><option value="1">1 mês</option><option value="12">12 meses</option><option value="all">Desde o início</option></select></label>{!benchmark&&<button className="secondary" onClick={()=>runBenchmarks(period)} disabled={benchmarkLoading}>Carregar referências</button>}</div>{benchmarkLoading&&<p className="muted">Carregando séries oficiais…</p>}{benchmark?.error&&<p className="notice danger">{benchmark.error}</p>}{benchmark&&<div className="benchmark-grid"><div><span>Sua carteira · retorno pessoal</span><strong>{personalReturn?`${(personalReturn.total*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`:'Histórico insuficiente'}</strong></div>{benchmark.results?.map(r=><div key={r.id}><span>{r.label}</span><strong>{r.return==null?'Sem dados':`${(r.return*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`}</strong><small>{r.updatedAt?`Atualizado ${fmtDate(r.updatedAt)}`:r.error||''}</small></div>)}</div>}<p className="source-note">CDI e IPCA: séries públicas do Banco Central (SGS). Ibovespa: estatísticas públicas da B3. Dados de índices não incluem impostos, custos ou dividendos reinvestidos.</p></Card>
  </>}
  {section==='transactions'&&<>
   <Card title="Registrar movimentação" icon={ReceiptText}><form key={month} onSubmit={addTransaction}><label>Tipo<select name="type" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="form-grid"><label>Data<input name="date" type="date" defaultValue={selectedDate} min={FINANCE_HISTORY_START} max={dateISO()} required/></label><label>Valor (R$)<input name="amount" type="number" min=".01" step=".01" required/></label></div><label>Descrição<input name="description" required maxLength="160" placeholder="Ex.: supermercado ou salário"/></label>{['income','expense','transfer','investment'].includes(type)&&<label>{type==='transfer'?'Conta de origem':'Conta'}<select name="accountId" required>{finance.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}{type==='transfer'&&<label>Conta de destino<select name="toAccountId" required>{finance.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}{type==='investment'&&<label>Investimento de destino<select name="assetId" required>{state.assets.filter(a=>a.id!=='cash').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}{['income','expense','card_purchase'].includes(type)&&<label>Categoria<select name="category">{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label>}{type==='card_purchase'&&<><label>Cartão<select name="cardId" required>{finance.cards.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Parcelas<input name="installments" type="number" min="1" max="48" defaultValue="1" required/></label></>}{type==='card_payment'&&<label>Fatura<select name="invoiceKey" required>{invoices.filter(i=>i.open>0).map(i=><option key={`${i.cardId}-${i.invoiceMonth}`} value={`${i.cardId}|${i.invoiceMonth}`}>{i.cardName} · {i.invoiceMonth} · em aberto {money(i.open)}</option>)}</select></label>}{['income','expense'].includes(type)&&<label className="checkbox"><input type="checkbox" name="recurring"/>Repetir mensalmente</label>}<p className="form-hint">{type==='card_payment'?'O pagamento reduz o saldo da conta e da fatura, sem duplicar a despesa.':type==='transfer'?'Transferências entre contas próprias não contam como receita nem despesa.':type==='investment'?'O aporte reduz o saldo bancário e entra uma vez no patrimônio investido.':type==='card_purchase'?'A compra entra no orçamento pela data da compra; parcelas aparecem nas faturas.':type==='income'?'Receitas aumentam o fluxo e o saldo da conta, mas não o patrimônio investido.':'Lançamentos são registrados no mês selecionado.'}</p><button className="primary full" disabled={busy||!finance.accounts.length||(type==='card_purchase'&&!finance.cards.length)||(type==='card_payment'&&!invoices.some(i=>i.open>0))}>Salvar lançamento</button></form></Card>
   {visibleTransactions.some(t=>t.needsReview)&&<p className="notice">Há movimentações importadas com categoria desconhecida ou possível transferência. Confira-as antes de usar os totais como definitivos.</p>}   <Card title="Lançamentos do mês" icon={ReceiptText}><div className="finance-filters"><input aria-label="Buscar lançamentos" placeholder="Buscar descrição…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar por tipo" value={filterType} onChange={e=>setFilterType(e.target.value)}><option value="all">Todos os tipos</option>{Object.entries(TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar por categoria" value={filterCategory} onChange={e=>setFilterCategory(e.target.value)}><option value="all">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filtrar por conta ou cartão" value={filterAccount} onChange={e=>setFilterAccount(e.target.value)}><option value="all">Todas as contas</option>{finance.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}{finance.cards.map(c=><option key={c.id} value={c.accountId}>{c.name}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Categoria / cartão</th><th>Valor</th><th></th></tr></thead><tbody>{visibleTransactions.map(t=><tr key={t.id}><td>{fmtDate(t.date)}</td><td><span className="tag neutral">{TYPES[t.type]}</span>{t.installments>1&&<small className="block">{t.installments} parcelas</small>}</td><td>{t.description}</td><td>{t.category||finance.cards.find(c=>c.id===t.cardId)?.name||'—'}{t.type==='card_purchase'&&<small className="block">Fatura {t.invoiceMonth}</small>}</td><td><strong>{display(t.amount)}</strong></td><td><button className="icon-button" aria-label={`Excluir ${t.description}`} onClick={()=>deleteTransaction(t)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!visibleTransactions.length&&<p className="muted">Nenhum lançamento corresponde a este mês e aos filtros.</p>}</div></Card>
   <Card title="Lançamentos recorrentes" icon={Repeat}><p className="muted">Gere as ocorrências apenas quando necessário. Cada recorrência entra uma vez no mês selecionado.</p>{finance.recurring.map(r=><div className="finance-row" key={r.id}><span className="finance-row-icon">{r.type==='income'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><span><strong>{r.description}</strong><small>Dia {r.day} · {r.category}</small></span><strong>{display(r.amount)}</strong></div>)}{finance.recurring.length>0&&<button className="secondary" onClick={addRecurring} disabled={busy}><Check size={16}/>Gerar recorrentes de {fmtMonth(month)}</button>}</Card>
  </>}
  {section==='budget'&&<Card title={`Orçamento de ${fmtMonth(month)}`} icon={CalendarDays}><p className="muted">Despesas à vista e compras no cartão entram pela data da compra. Pagar a fatura não lança a despesa novamente.</p><form onSubmit={saveBudget}>{categories.map(c=>{const spent=summary.expensesByCategory[c]||0,limit=Number(budgetValues[c]||0);return <label className="budget-row" key={c}><span>{c}<small>{display(spent)} gasto{limit>0?` de ${display(limit)}`:''}</small></span><input aria-label={`Limite para ${c}`} type="number" min="0" step=".01" value={budgetValues[c]??''} placeholder="Sem limite" onChange={e=>setBudgetValues({...budgetValues,[c]:e.target.value})}/>{limit>0&&<i style={{'--budget-progress':`${Math.min(100,spent/limit*100)}%`}}/>}</label>})}<button className="primary full" disabled={busy}>Salvar orçamento do mês</button></form><form className="inline-form spaced" onSubmit={addCategory}><label>Nova categoria<input name="category" maxLength="60" placeholder="Ex.: Pets" required/></label><button className="secondary" disabled={busy}>Adicionar categoria</button></form></Card>}
  {section==='cards'&&<><section className="finance-layout spaced"><Card title="Cartões cadastrados" icon={CreditCard}>{finance.cards.map(c=><div className="finance-row" key={c.id}><span className="finance-row-icon"><CreditCard size={17}/></span><span><strong>{c.name}</strong><small>Fecha dia {c.closeDay} · vence dia {c.dueDay}</small></span><strong>{finance.accounts.find(a=>a.id===c.accountId)?.name||'Conta não encontrada'}</strong></div>)}{!finance.cards.length&&<p className="muted">Cadastre um cartão para acompanhar compras, parcelas e faturas.</p>}<button className="secondary full" onClick={()=>setShowCard(!showCard)}><Plus size={16}/>Adicionar cartão</button>{showCard&&<form className="inline-form spaced" onSubmit={addCard}><label>Nome do cartão<input name="name" required maxLength="80" placeholder="Ex.: Santander Visa"/></label><label>Conta usada para pagar<select name="accountId" required>{finance.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="form-grid"><label>Dia de fechamento<input name="closeDay" type="number" min="1" max="28" defaultValue="10" required/></label><label>Dia de vencimento<input name="dueDay" type="number" min="1" max="28" defaultValue="20" required/></label></div><button className="primary" disabled={busy||!finance.accounts.length}>Salvar cartão</button></form>}</Card>
   <Card title={`Faturas da competência · ${fmtMonth(month)}`} icon={ReceiptText}>{monthInvoices.map(i=><div className="finance-row" key={`${i.cardId}-${i.invoiceMonth}`}><span className="finance-row-icon"><CreditCard size={17}/></span><span><strong>{i.cardName}</strong><small>{i.open===0?'Paga':`Vence ${fmtDate(i.dueDate)}`} · total {display(i.total)} · pago {display(i.paid)}</small></span><strong>{display(i.open)}</strong></div>)}{!monthInvoices.length&&<p className="muted">Nenhuma fatura nesta competência.</p>}</Card>
  </section><Card title="Parcelas desta fatura" icon={CalendarDays}>{monthInvoices.flatMap(i=>i.purchases.map((p,index)=><div className="finance-row" key={`${i.cardId}-${i.invoiceMonth}-${index}`}><span className="finance-row-icon"><ReceiptText size={17}/></span><span><strong>{p.description}</strong><small>{p.category||'Outros'} · vencimento {fmtDate(p.dueDate)}</small></span><strong>{display(p.amount)}</strong></div>))}{!monthInvoices.some(i=>i.purchases.length)&&<p className="muted">As compras parceladas aparecerão aqui por competência.</p>}</Card></>}
  {section==='accounts'&&<Card title="Contas e saldo disponível" icon={Wallet}>{finance.accounts.map(a=><div className="finance-row" key={a.id}><span className="finance-row-icon"><Wallet size={17}/></span><span><strong>{a.name}</strong><small>{a.type==='checking'?'Conta corrente':a.type==='savings'?'Poupança':'Dinheiro'} · saldo em {fmtDate(asOf)}</small></span><strong>{display(balances[a.id]||0)}</strong><button className="icon-button" aria-label={`Excluir conta ${a.name}`} title="Excluir conta" disabled={busy} onClick={()=>deleteAccount(a)}><Trash2 size={16}/></button></div>)}{!finance.accounts.length&&<p className="muted">Cadastre sua conta para acompanhar receitas e despesas.</p>}<button className="secondary full" onClick={()=>setShowAccount(!showAccount)}><Plus size={16}/>Adicionar conta</button>{showAccount&&<form className="inline-form spaced" onSubmit={addAccount}><label>Nome<input name="name" required maxLength="80" placeholder="Ex.: Santander conta corrente"/></label><div className="form-grid"><label>Tipo<select name="type"><option value="checking">Conta corrente</option><option value="savings">Poupança</option><option value="cash">Dinheiro / carteira</option></select></label><label>Saldo inicial<input name="openingBalance" type="number" step=".01" defaultValue="0"/></label></div><label>Data do saldo inicial<input name="openingDate" type="date" min={FINANCE_HISTORY_START} max={dateISO()} defaultValue={dateISO()}/></label><button className="primary" disabled={busy}>Salvar conta</button></form>}</Card>}
  {section==='import'&&<>
   <Card title="Conectar Meu Pluggy" icon={Wallet}><p className="muted">Cole o Item ID da conexão Santander que você associou à aplicação demo. O ID fica salvo na carteira privada do Supabase. A sincronização consulta apenas contas e transações bancárias; credenciais Pluggy permanecem no servidor. Transferências e categorias desconhecidas serão marcadas para revisão.</p><form className="inline-form" onSubmit={savePluggyItem}><label>Item ID<input value={pluggyItemId} onChange={e=>setPluggyItemId(e.target.value)} autoComplete="off" spellCheck="false" placeholder="Cole o Item ID" required/></label><div className="button-row"><button className="primary" disabled={busy}>Salvar Item ID</button><button className="secondary" type="button" onClick={syncPluggy} disabled={busy||!finance.pluggy?.itemId}>{busy?'Sincronizando…':'Atualizar agora'}</button>{finance.pluggy?.lastSyncAt&&<span className="muted small">Última atualização: {new Date(finance.pluggy.lastSyncAt).toLocaleString('pt-BR')}</span>}</div></form><p className="source-note">Conexão pessoal atualizada pelo Meu Pluggy diariamente. O app também fará uma consulta diária pela rotina da Vercel e permite atualização sob demanda. Contas de cartão e investimentos não são importadas nesta primeira etapa para evitar duplicar despesas ou patrimônio.</p></Card>
   <Card title="Importar ou exportar CSV" icon={Upload}><p className="muted">CSV e lançamentos manuais continuam disponíveis. A prévia detecta duplicados e linhas suspeitas antes de importar.</p><input ref={csvRef} hidden type="file" accept=".csv,text/csv" onChange={loadCsv}/><div className="button-row"><button className="secondary" onClick={()=>csvRef.current?.click()}><Upload size={16}/>Selecionar arquivo CSV</button><button className="secondary" onClick={exportFinanceCsv}><Download size={16}/>Exportar controle</button>{csvRows&&<label>Conta<select value={csvAccount} onChange={e=>setCsvAccount(e.target.value)}>{finance.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</div>{csvRows&&<><div className="toolbar"><span>{csvRows.filter(r=>r.selected&&!r.duplicate).length} selecionadas · {csvRows.filter(r=>r.duplicate).length} duplicadas · {csvRows.filter(r=>!r.valid).length} inválidas</span><label>Categoria padrão das despesas<select value={csvCategory} onChange={e=>setCsvCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Importar</th><th>Data</th><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Status</th></tr></thead><tbody>{csvRows.slice(0,1000).map((r,i)=><tr key={`${r.row}-${i}`}><td><input type="checkbox" checked={r.selected} disabled={!r.valid||r.duplicate} onChange={e=>setCsvRows(csvRows.map((x,j)=>j===i?{...x,selected:e.target.checked}:x))}/></td><td>{r.date}</td><td>{r.description||'—'}</td><td>{r.type==='income'?'Receita':r.type==='review'?'Revisar transferência / cartão':'Despesa'}</td><td>{r.valid?display(r.amount):'—'}</td><td>{r.possibleTransfer?'Lance manualmente para evitar duplicidade':r.duplicate?'Duplicada':!r.valid?'Inválida':'Nova'}</td></tr>)}</tbody></table>{csvRows.length>1000&&<p className="muted">Mostrando as primeiras 1.000 linhas.</p>}</div><div className="button-row spaced"><button className="primary" onClick={importCsv} disabled={busy||!csvAccount}>Importar selecionadas</button><button className="secondary" onClick={()=>setCsvRows(null)}>Cancelar</button></div></>}</Card>
  </>}
 </div>;
}
