'use client';

import {useState} from 'react';
import {ArrowRight,Info,Landmark,Plus,Search} from 'lucide-react';
import {CATEGORIES,COLORS,moneyWeightedReturn} from '../lib/portfolio.mjs';
import {allocationByInstitution,investmentPositions} from '../lib/investment-view.mjs';

const fmtDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');

export function Investments({state,calc,display,onAdd,onClose,onEdit}){
 const [search,setSearch]=useState(''),[institution,setInstitution]=useState('all');
 const positions=investmentPositions(state),allocation=allocationByInstitution(positions),total=positions.reduce((sum,p)=>sum+p.value,0),returnData=moneyWeightedReturn(state);
 const visible=positions.filter(p=>(institution==='all'||p.institution===institution)&&`${p.asset.name} ${p.asset.ticker||''} ${p.institution} ${CATEGORIES[p.asset.category]}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 return <div className="investments-page">
  <section className="panel investment-summary"><div><span className="eyebrow">CARTEIRA CONJUNTA</span><h2>Patrimônio investido</h2><strong>{display(calc.total)}</strong><p>Saldo das posições e caixa de dividendos. Saldos bancários ficam no Controle financeiro.</p><small className="muted">O resultado desconta aportes e retiradas; o retorno pessoal considera as datas de cada movimento.</small></div><div className="investment-summary-numbers"><div><span>Capital líquido aportado</span><b>{display(calc.netInvested)}</b></div><div><span>Resultado acumulado</span><b className={calc.gain<0?'negative':''}>{display(calc.gain)}</b></div><div><span>Retorno pessoal</span><b>{returnData?`${(returnData.total*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`:'Histórico insuficiente'}</b></div></div></section>
  <section className="panel investment-institutions"><div className="panel-heading"><div><h2>Alocação por instituição</h2><p>Conforme a instituição informada em cada posição. Caixa de dividendos separado.</p></div><Landmark size={18}/></div>{allocation.length?<><div className="investment-allocation-track" role="img" aria-label="Distribuição por instituição">{allocation.map((row,index)=><i key={row.institution} style={{width:`${total?row.value/total*100:0}%`,background:['var(--lime)','#b5d5d1','#aa9eb8','#7c7a7f'][index%4]}}/>)}</div><div className="investment-institution-list">{allocation.map((row,index)=><button key={row.institution} className={institution===row.institution?'selected':''} onClick={()=>setInstitution(institution===row.institution?'all':row.institution)}><i style={{background:['var(--lime)','#b5d5d1','#aa9eb8','#7c7a7f'][index%4]}}/><span>{row.institution}</span><strong>{display(row.value)}</strong><small>{total?(row.value/total*100).toLocaleString('pt-BR',{maximumFractionDigits:1}):'0'}%</small></button>)}</div></>:<p className="muted">Adicione posições para ver a distribuição.</p>}{calc.values.cash>0&&<p className="muted small">Caixa de dividendos: {display(calc.values.cash)}</p>}</section>
  <section className="panel investment-position-panel"><div className="panel-heading"><div><h2>Posições</h2><p>Confira quando e de onde veio o último saldo registrado.</p></div><span className="tag neutral">{visible.length} de {positions.length}</span></div><div className="investment-toolbar"><div className="search"><Search size={17}/><input aria-label="Buscar investimento" placeholder="Buscar nome, classe ou instituição…" value={search} onChange={event=>setSearch(event.target.value)}/></div><select aria-label="Filtrar instituição" value={institution} onChange={event=>setInstitution(event.target.value)}><option value="all">Todas as instituições</option>{allocation.map(row=><option key={row.institution}>{row.institution}</option>)}</select><button className="secondary" onClick={onAdd}><Plus size={16}/>Adicionar ativo</button><button className="secondary" onClick={onClose}>Atualizar saldos</button></div>{visible.length?<div className="investment-position-grid">{visible.map(position=>{const asset=position.asset;return <article className="investment-position" key={asset.id}><div className="investment-position-top"><span className="investment-position-icon" style={{color:COLORS[asset.category]}}><Landmark size={19}/></span><div><h3>{asset.name}</h3><span>{CATEGORIES[asset.category]}{asset.ticker?` · ${asset.ticker}`:''}</span></div><button className="text-button" aria-label={`Editar ${asset.name}`} onClick={()=>onEdit(asset)}>Editar <ArrowRight size={14}/></button></div><strong className="investment-position-value">{display(position.value)}</strong><div className="investment-position-meta"><span>Instituição</span><b>{position.institution}</b><span>Origem do saldo</span><b>{position.source}</b><span>Data do saldo</span><b>{position.balanceDate?fmtDate(position.balanceDate):'Sem conferência registrada'}</b>{position.linked&&<><span>Conexão</span><b>{position.remoteDate?`Meu Pluggy · ${fmtDate(position.remoteDate)}`:'Meu Pluggy · sem data'}</b></>}</div>{asset.reserve&&<span className="tag green">Reserva</span>}</article>})}</div>:<p className="muted">Nenhuma posição corresponde à busca ou ao filtro.</p>}</section>
  <details className="panel investment-return-note"><summary>Como o resultado e a rentabilidade são calculados</summary><p>Resultado acumulado = patrimônio atual − saldo inicial − aportes + retiradas. Os dividendos que continuam na carteira já fazem parte do patrimônio e não são somados outra vez. Transferências internas e reinvestimentos não são novos aportes.</p><p>O retorno pessoal considera as datas dos aportes e retiradas. Ele depende de saldos informados ou sincronizados: uma posição sem conferência recente pode mostrar patrimônio e retorno desatualizados. Preço médio e quantidade são informativos; não substituem o saldo registrado.</p></details>
 </div>;
}
