'use client';

import {useState} from 'react';
import {ArrowLeft,ArrowRight,BarChart3} from 'lucide-react';
import {dateISO} from '../lib/portfolio.mjs';
import {financeReport,reportTransactions} from '../lib/reports.mjs';

const fmtMonth=value=>new Date(`${value}-15T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
const fmtDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');
const label={income:'Receita',expense:'Despesa',card_purchase:'Compra no cartão',card_payment:'Pagamento de fatura',investment:'Aporte debitado da conta'};

export function Reports({finance,events=[],display}){
 const current=dateISO().slice(0,7),startMonth=[...finance.accounts.map(a=>a.openingDate?.slice(0,7)),...finance.transactions.map(t=>t.date?.slice(0,7))].filter(Boolean).sort()[0]||current,[period,setPeriod]=useState('month'),[anchor,setAnchor]=useState(current),[view,setView]=useState('accrual'),[detailMonth,setDetailMonth]=useState(current),[kind,setKind]=useState('all'),[category,setCategory]=useState('all');
 const years=Array.from({length:Math.max(1,Number(current.slice(0,4))-Number(startMonth.slice(0,4))+1)},(_,index)=>String(Number(startMonth.slice(0,4))+index));
 const report=financeReport(finance,{period,anchor,events}),rows=report.rows,selected=period==='month'?anchor:detailMonth,detail=rows.find(row=>row.month===selected),transactions=reportTransactions(finance,selected,{view,kind,category,events});
 const base=report.rows.reduce((maximum,row)=>Math.max(maximum,row.income,view==='cash'?row.cashExpenses+row.cashInvestments:row.accrualExpenses),1);
 const navigate=offset=>{if(period==='year'){const year=String(Number(anchor.slice(0,4))+offset);if(year<=current.slice(0,4)){setAnchor(`${year}-01`);setDetailMonth(`${year}-01`);}}else{const day=new Date(`${anchor}-15T12:00:00Z`);day.setUTCMonth(day.getUTCMonth()+offset);const next=day.toISOString().slice(0,7);if(next<=current){setAnchor(next);setDetailMonth(next);}}setKind('all');setCategory('all');};
 const choosePeriod=value=>{setPeriod(value);setAnchor(value==='year'?`${anchor.slice(0,4)}-01`:current);setDetailMonth(value==='year'?`${anchor.slice(0,4)}-01`:current);setKind('all');setCategory('all');};
 const selectMonth=month=>{setDetailMonth(month);setKind('all');setCategory('all');};
 return <div className="reports-page">
  <section className="panel reports-controls"><div><span className="eyebrow">RELATÓRIOS</span><h2>{period==='year'?anchor.slice(0,4):fmtMonth(anchor)}</h2><p>Valores confirmados dos lançamentos cadastrados ou sincronizados.</p></div><div className="reports-controls-actions"><div className="segmented" role="group" aria-label="Período do relatório"><button className={period==='month'?'selected':''} onClick={()=>choosePeriod('month')}>Mensal</button><button className={period==='year'?'selected':''} onClick={()=>choosePeriod('year')}>Anual</button></div>{period==='month'?<input aria-label="Mês do relatório" type="month" min={startMonth} max={current} value={anchor} onChange={event=>{setAnchor(event.target.value);setDetailMonth(event.target.value);setKind('all');setCategory('all')}}/>:<select aria-label="Ano do relatório" value={anchor.slice(0,4)} onChange={event=>{setAnchor(`${event.target.value}-01`);setDetailMonth(`${event.target.value}-01`);setKind('all');setCategory('all')}}>{years.map(year=><option key={year}>{year}</option>)}</select>}<div className="reports-stepper"><button className="icon-button" aria-label="Período anterior" disabled={period==='month'?anchor<=startMonth:anchor.slice(0,4)<=startMonth.slice(0,4)} onClick={()=>navigate(-1)}><ArrowLeft size={17}/></button><button className="icon-button" aria-label="Próximo período" disabled={period==='year'?anchor.slice(0,4)>=current.slice(0,4):anchor>=current} onClick={()=>navigate(1)}><ArrowRight size={17}/></button></div></div></section>
  <section className="panel reports-view"><div className="panel-heading"><div><h2>Qual leitura você quer ver?</h2><p>Competência mostra o gasto no mês da compra. Caixa mostra quando o dinheiro saiu da conta.</p></div><BarChart3 size={18}/></div><div className="segmented" role="group" aria-label="Leitura do relatório"><button className={view==='accrual'?'selected':''} onClick={()=>{setView('accrual');setKind('all');setCategory('all')}}>Por competência</button><button className={view==='cash'?'selected':''} onClick={()=>{setView('cash');setKind('all');setCategory('all')}}>Movimentação de caixa</button></div><div className="reports-metrics"><div><span>Receitas</span><strong>{display(report.income)}</strong></div><div><span>{view==='cash'?'Saídas da conta':'Gastos do período'}</span><strong>{display(view==='cash'?report.cashExpenses+report.cashInvestments:report.accrualExpenses)}</strong></div><div><span>{view==='cash'?'Variação de caixa':'Resultado por competência'}</span><strong className={(view==='cash'?report.cashResult:report.accrualResult)<0?'negative':''}>{display(view==='cash'?report.cashResult:report.accrualResult)}</strong></div><div><span>Aportes à carteira</span><strong>{display(report.investments)}</strong></div><div><span>Para revisar</span><strong>{report.pending}</strong></div></div><p className="muted small">{view==='cash'?`Saídas: despesas à vista, faturas pagas e aportes. As compras no cartão entram aqui quando a fatura é paga. A variação não inclui transferências entre contas próprias nem saldos iniciais.`:`Gastos: despesas à vista e compras no cartão na data da compra. Aportes e pagamentos de fatura não são novas despesas.`}</p></section>
  <section className="panel reports-chart"><div className="panel-heading"><h2>{period==='year'?'Evolução mensal':'Resumo do mês'}</h2><span className="muted small">Toque em um mês para ver os registros</span></div><div className="reports-bars">{rows.map(row=><button key={row.month} className={detail?.month===row.month?'selected':''} disabled={!row.hasData} onClick={()=>selectMonth(row.month)} aria-label={`${fmtMonth(row.month)}: receitas ${display(row.income)}, saídas ${display(view==='cash'?row.cashExpenses+row.cashInvestments:row.accrualExpenses)}`}><span className="reports-bar-pair"><i style={{height:`${Math.max(2,row.income/base*100)}%`}}/><i style={{height:`${Math.max(2,(view==='cash'?row.cashExpenses+row.cashInvestments:row.accrualExpenses)/base*100)}%`}}/></span><span>{new Date(`${row.month}-15T12:00:00`).toLocaleDateString('pt-BR',{month:'short'})}</span>{!row.hasData&&<small>Sem dados</small>}</button>)}</div><div className="reports-legend"><span><i/>Receitas</span><span><i/>Saídas</span></div></section>
  <section className="panel reports-detail"><div className="panel-heading"><div><h2>Detalhes de {fmtMonth(selected)}</h2><p>{detail?.hasData?'Selecione um tipo ou categoria para abrir os lançamentos.':'Não há contas ou lançamentos registrados neste mês.'}</p></div></div>{detail?.hasData&&<><div className="reports-breakdown"><button onClick={()=>{setKind('income');setCategory('all')}}><span>Receitas</span><strong>{display(detail.income)}</strong></button><button onClick={()=>{setKind('expenses');setCategory('all')}}><span>{view==='cash'?'Despesas e faturas pagas':'Despesas e compras'}</span><strong>{display(view==='cash'?detail.cashExpenses:detail.accrualExpenses)}</strong></button><button onClick={()=>{setKind('investments');setCategory('all')}}><span>Aportes à carteira</span><strong>{display(detail.investments)}</strong></button></div>{view==='accrual'&&detail.categories.length>0&&<div className="reports-categories"><h3>Gastos por categoria</h3>{detail.categories.map(row=><button key={row.name} onClick={()=>{setKind('expenses');setCategory(row.name)}}><span>{row.name}</span><strong>{display(row.value)}</strong><i style={{width:`${detail.accrualExpenses?row.value/detail.accrualExpenses*100:0}%`}}/></button>)}</div>}<div className="reports-ledger"><div className="panel-heading"><h3>Lançamentos {category!=='all'?`· ${category}`:kind!=='all'?`· ${kind==='income'?'receitas':kind==='investments'?'aportes':'saídas'}`:''}</h3><button className="text-button" onClick={()=>{setKind('all');setCategory('all')}}>Mostrar todos</button></div>{transactions.length?transactions.map(t=><div className="reports-entry" key={t.id}><span><strong>{t.description}</strong><small>{fmtDate(t.date)} · {label[t.type]} · {t.category||'Sem categoria'}</small></span><b>{display(t.amount)}</b></div>):<p className="muted">Nenhum lançamento confirmado corresponde ao filtro.</p>}</div></>}</section>
 </div>;
}
