export const FINANCE_TYPES=['checking','savings','cash'];
export const FINANCE_CATEGORIES=['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Contas','Compras','Salário','Rendimentos','Outros'];
export const DEFAULT_FINANCE=()=>({accounts:[],cards:[],transactions:[],recurring:[],budgets:{},categories:[]});
const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const monthOf=d=>d.slice(0,7);
const dateISO=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const shiftMonth=(month,n)=>{const d=new Date(`${month}-15T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,7)};
export function validateFinance(f,assets=[],events=[],startDate='2000-01-01'){
 if(f==null)return true;
 if(!f||typeof f!=='object'||Array.isArray(f)||!Array.isArray(f.accounts)||!Array.isArray(f.cards)||!Array.isArray(f.transactions)||!Array.isArray(f.recurring)||!f.budgets||typeof f.budgets!=='object'||Array.isArray(f.budgets)||(f.categories!=null&&(!Array.isArray(f.categories)||f.categories.length>100||f.categories.some(c=>typeof c!=='string'||!c.trim()||c.length>60))))throw new Error('Dados financeiros inválidos.');
 if(f.accounts.length>100||f.cards.length>30||f.transactions.length>20000||f.recurring.length>500)throw new Error('Limite de dados financeiros excedido.');
 const accountIds=new Set(),cardIds=new Set(),txIds=new Set(),assetIds=new Set(assets.map(a=>a.id)),eventIds=new Set(events.map(e=>e.id));
 for(const a of f.accounts){if(!a||typeof a.id!=='string'||!a.id||accountIds.has(a.id)||typeof a.name!=='string'||!a.name.trim()||a.name.length>80||!FINANCE_TYPES.includes(a.type)||!Number.isFinite(a.openingBalance)||Math.abs(a.openingBalance)>1e12||!validDate(a.openingDate)||a.openingDate<'2000-01-01'||a.openingDate>dateISO())throw new Error('Conta financeira inválida.');accountIds.add(a.id);}
 for(const c of f.cards){if(!c||typeof c.id!=='string'||!c.id||cardIds.has(c.id)||typeof c.name!=='string'||!c.name.trim()||c.name.length>80||!accountIds.has(c.accountId)||!Number.isInteger(c.closeDay)||c.closeDay<1||c.closeDay>28||!Number.isInteger(c.dueDay)||c.dueDay<1||c.dueDay>28)throw new Error('Cartão inválido.');cardIds.add(c.id);}
 for(const t of f.transactions){if(!t||typeof t.id!=='string'||!t.id||txIds.has(t.id)||!['income','expense','transfer','investment','card_purchase','card_payment'].includes(t.type)||!Number.isFinite(t.amount)||t.amount<=0||t.amount>1e12||!validDate(t.date)||t.date<'2000-01-01'||t.date>dateISO()||typeof t.description!=='string'||!t.description.trim()||t.description.length>160)throw new Error('Lançamento financeiro inválido.');txIds.add(t.id);
  if(['income','expense','transfer','investment','card_payment'].includes(t.type)&&!accountIds.has(t.accountId))throw new Error('Conta do lançamento não encontrada.');if(['income','expense','transfer','investment','card_payment'].includes(t.type)&&t.date<f.accounts.find(a=>a.id===t.accountId).openingDate)throw new Error('O lançamento é anterior ao saldo inicial da conta.');
  if(t.type==='transfer'&&(!accountIds.has(t.toAccountId)||t.toAccountId===t.accountId||t.date<f.accounts.find(a=>a.id===t.toAccountId).openingDate))throw new Error('Conta de destino da transferência inválida.');
  if(t.type==='investment'&&(!assetIds.has(t.assetId)||!eventIds.has(t.portfolioEventId)))throw new Error('Vínculo com o investimento inválido.');
  if(t.type==='card_purchase'&&(!cardIds.has(t.cardId)||!Number.isInteger(t.installments)||t.installments<1||t.installments>48||!Number.isInteger(t.closeDay)||t.closeDay<1||t.closeDay>28||!Number.isInteger(t.dueDay)||t.dueDay<1||t.dueDay>28||typeof t.invoiceMonth!=='string'||!/^\d{4}-\d{2}$/.test(t.invoiceMonth)))throw new Error('Compra no cartão inválida.');
  if(t.type==='card_purchase'&&t.installmentParts!=null&&(!Array.isArray(t.installmentParts)||t.installmentParts.length!==t.installments||t.installmentParts.some(p=>!p||typeof p.invoiceMonth!=='string'||!/^\d{4}-\d{2}$/.test(p.invoiceMonth)||!validDate(p.dueDate)||!Number.isFinite(p.amount)||p.amount<=0||!Number.isInteger(p.installment)||p.installment<1||p.installment>t.installments)))throw new Error('Parcelas do cartão inválidas.');
  if(t.type==='card_payment'&&(!cardIds.has(t.cardId)||typeof t.invoiceMonth!=='string'||!/^\d{4}-\d{2}$/.test(t.invoiceMonth)))throw new Error('Pagamento de fatura inválido.');
  if(t.category!=null&&(typeof t.category!=='string'||t.category.length>60))throw new Error('Categoria inválida.');
  if(t.recurringId!=null&&typeof t.recurringId!=='string')throw new Error('Recorrência inválida.');
 }
 for(const t of f.transactions.filter(t=>t.type==='card_purchase'&&Array.isArray(t.installmentParts))){const total=t.installmentParts.reduce((n,p)=>n+p.amount,0);if(Math.abs(total-t.amount)>.02)throw new Error('O total das parcelas precisa corresponder à compra.');}
 for(const t of f.transactions.filter(t=>t.type==='card_payment')){const card=f.cards.find(c=>c.id===t.cardId);if(!card||card.accountId!==t.accountId)throw new Error('Conta de pagamento da fatura não corresponde ao cartão.');const purchased=f.transactions.filter(p=>p.type==='card_purchase'&&p.cardId===t.cardId).flatMap(p=>purchaseParts(p)).filter(p=>p.invoiceMonth===t.invoiceMonth).reduce((n,p)=>n+p.amount,0);const paid=f.transactions.filter(p=>p.type==='card_payment'&&p.cardId===t.cardId&&p.invoiceMonth===t.invoiceMonth).reduce((n,p)=>n+p.amount,0);if(paid>purchased+.02)throw new Error('Pagamentos da fatura excedem o total das compras.');}
 const recurringIds=new Set();for(const r of f.recurring){if(!r||typeof r.id!=='string'||!r.id||recurringIds.has(r.id)||!['income','expense'].includes(r.type)||typeof r.description!=='string'||!r.description.trim()||!Number.isFinite(r.amount)||r.amount<=0||!accountIds.has(r.accountId)||!Number.isInteger(r.day)||r.day<1||r.day>28||typeof r.category!=='string')throw new Error('Regra recorrente inválida.');recurringIds.add(r.id);}
 for(const [m,v] of Object.entries(f.budgets))if(!/^\d{4}-\d{2}$/.test(m)||!v||typeof v!=='object'||Array.isArray(v)||Object.values(v).some(x=>!Number.isFinite(x)||x<0||x>1e12))throw new Error('Orçamento inválido.');
 return true;
}
export function statementMonth(date,closeDay){const m=monthOf(date);return Number(date.slice(8,10))>closeDay?shiftMonth(m,1):m;}
export function invoiceDueDate(invoiceMonth,dueDay,closeDay=28){const m=Number(dueDay)<=Number(closeDay)?shiftMonth(invoiceMonth,1):invoiceMonth;return `${m}-${String(Math.min(dueDay,28)).padStart(2,'0')}`;}
export function installmentSchedule({date,amount,installments=1,closeDay=10,dueDay=20}){const first=statementMonth(date,closeDay);const each=Math.round((amount/installments)*100)/100;return Array.from({length:installments},(_,i)=>({invoiceMonth:shiftMonth(first,i),dueDate:invoiceDueDate(shiftMonth(first,i),dueDay,closeDay),amount:i===installments-1?Math.round((amount-each*(installments-1))*100)/100:each,installment:i+1,installments}));}
export function accountBalances(finance,asOf=dateISO()){const out=Object.fromEntries(finance.accounts.map(a=>[a.id,a.openingDate<=asOf?a.openingBalance:0]));for(const t of finance.transactions.filter(t=>t.date<=asOf)){if(t.type==='income'&&t.accountId in out)out[t.accountId]+=t.amount;if(t.type==='expense'&&t.accountId in out)out[t.accountId]-=t.amount;if(t.type==='transfer'){if(t.accountId in out)out[t.accountId]-=t.amount;if(t.toAccountId in out)out[t.toAccountId]+=t.amount;}if(t.type==='investment'&&t.accountId in out)out[t.accountId]-=t.amount;if(t.type==='card_payment'&&t.accountId in out)out[t.accountId]-=t.amount;}return out;}
function purchaseParts(t){if(Array.isArray(t.installmentParts))return t.installmentParts;return [{invoiceMonth:t.invoiceMonth,amount:t.amount,dueDate:t.dueDate}];}
export function invoiceSummaries(finance,asOf=dateISO()){const result=[];for(const card of finance.cards){const purchases=finance.transactions.filter(t=>t.type==='card_purchase'&&t.cardId===card.id&&t.date<=asOf);const payments=finance.transactions.filter(t=>t.type==='card_payment'&&t.cardId===card.id&&t.date<=asOf);const months=new Set([...purchases.flatMap(t=>purchaseParts(t).map(p=>p.invoiceMonth)),...payments.map(t=>t.invoiceMonth)]);for(const invoiceMonth of months){const items=purchases.flatMap(t=>purchaseParts(t).filter(p=>p.invoiceMonth===invoiceMonth).map(p=>({amount:p.amount,description:t.description,category:t.category,dueDate:p.dueDate||invoiceDueDate(invoiceMonth,card.dueDay,card.closeDay)})));const paid=payments.filter(t=>t.invoiceMonth===invoiceMonth).reduce((n,t)=>n+t.amount,0);const total=items.reduce((n,p)=>n+p.amount,0);result.push({cardId:card.id,cardName:card.name,invoiceMonth,dueDate:invoiceDueDate(invoiceMonth,card.dueDay,card.closeDay),total,paid,open:Math.max(0,total-paid),purchases:items});}}return result.sort((a,b)=>a.dueDate.localeCompare(b.dueDate));}
export function monthEnd(month){const d=new Date(`${month}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return d.toISOString().slice(0,10);}
export function summarizeFinance(finance,month=monthOf(dateISO()),asOf=monthEnd(month)){const balances=accountBalances(finance,asOf),invoices=invoiceSummaries(finance,asOf),income=finance.transactions.filter(t=>t.type==='income'&&monthOf(t.date)===month).reduce((n,t)=>n+t.amount,0),expenses=finance.transactions.filter(t=>t.type==='expense'&&monthOf(t.date)===month).reduce((n,t)=>n+t.amount,0),cardSpend=finance.transactions.filter(t=>t.type==='card_purchase'&&monthOf(t.date)===month).reduce((n,t)=>n+t.amount,0),investments=finance.transactions.filter(t=>t.type==='investment'&&monthOf(t.date)===month).reduce((n,t)=>n+t.amount,0),budget=finance.budgets[month]||{};const expensesByCategory={};for(const t of finance.transactions)if((t.type==='expense'||t.type==='card_purchase')&&monthOf(t.date)===month)expensesByCategory[t.category||'Outros']=(expensesByCategory[t.category||'Outros']||0)+t.amount;const due=invoices.filter(i=>i.open>0&&monthOf(i.dueDate)===month).reduce((n,i)=>n+i.open,0);return {balances,cash:Object.values(balances).reduce((a,b)=>a+b,0),invoices,income,expenses:expenses+cardSpend,cardSpend,investments,due,budget,expensesByCategory,netCashFlow:income-expenses-cardSpend-investments};}
export function addMonthlyRecurring(finance,month=monthOf(dateISO())){const next=structuredClone(finance);let added=0;for(const r of next.recurring){if(next.transactions.some(t=>t.recurringId===r.id&&monthOf(t.date)===month))continue;const d=new Date(`${month}-01T12:00:00Z`),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate(),day=String(Math.min(r.day,last)).padStart(2,'0');const date=`${month}-${day}`;if(date>dateISO())continue;next.transactions.push({id:crypto.randomUUID(),type:r.type,accountId:r.accountId,amount:r.amount,date,description:r.description,category:r.category,recurringId:r.id});added++;}return {finance:next,added};}
export function parseStatementCsv(text,minDate='2000-01-01'){
 if(typeof text!=='string'||text.length>5_000_000)throw new Error('O CSV deve ter no máximo 5 MB.');
 const first=text.split(/\r?\n/,1)[0]||'',delimiter=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=!quoted;else if(ch===delimiter&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=ch;}
 if(quoted)throw new Error('O CSV tem aspas sem fechamento.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)throw new Error('O arquivo precisa ter cabeçalho e ao menos uma movimentação.');
 const headers=rows.shift().map(h=>h.trim().replace(/^\uFEFF/,'')),pick=names=>headers.findIndex(h=>names.some(n=>h.toLocaleLowerCase('pt-BR').includes(n))),dateIndex=pick(['data']),descriptionIndex=pick(['descri','histórico','historico','lançamento','lancamento']),amountIndex=pick(['valor','amount']);if(dateIndex<0||descriptionIndex<0||amountIndex<0)throw new Error('Não encontrei as colunas de data, descrição e valor no CSV.');
 const seen=new Set();return rows.map((cells,index)=>{const rawDate=(cells[dateIndex]||'').trim(),date=/^\d{2}\/\d{2}\/\d{4}$/.test(rawDate)?`${rawDate.slice(6)}-${rawDate.slice(3,5)}-${rawDate.slice(0,2)}`:rawDate.slice(0,10),description=(cells[descriptionIndex]||'').trim().slice(0,160),raw=(cells[amountIndex]||'').trim().replace(/R\$\s?/gi,'').replace(/\s/g,''),value=raw.includes(',')?Number(raw.replace(/\./g,'').replace(',','.')):Number(raw),possibleTransfer=/\b(transfer[eê]ncia|pix (enviado|recebido)|ted|doc|aplica[cç][aã]o|resgate|fatura|cart[aã]o)\b/i.test(description),fingerprint=[date,description.toLocaleLowerCase('pt-BR'),Math.abs(value).toFixed(2),value<0?'expense':'income'].join('|'),duplicateInFile=seen.has(fingerprint);seen.add(fingerprint);return {row:index+2,date,description,amount:Math.abs(value),type:possibleTransfer?'review':value<0?'expense':'income',category:value<0?'Outros':/sal[aá]rio|folha|remunera[cç][aã]o/i.test(description)?'Salário':'Rendimentos',possibleTransfer,duplicateInFile,valid:!possibleTransfer&&!duplicateInFile&&validDate(date)&&date>=minDate&&date<=dateISO()&&Number.isFinite(value)&&value!==0&&description.length>0};});
}
export function csvFingerprint(t){return [t.date,t.description.trim().toLocaleLowerCase('pt-BR'),t.amount.toFixed(2),t.type].join('|');}
export function importPreviewRows(rows,existing){const known=new Set(existing.map(csvFingerprint));return rows.map(r=>{const duplicate=known.has(csvFingerprint(r))||r.duplicateInFile;known.add(csvFingerprint(r));return {...r,duplicate,selected:r.valid&&!duplicate};});}
export {monthOf,shiftMonth};
